Importando as bibliotecas e módulos necessários:

In [2]:
!pip install openpyxl
import os
import pandas as pd
import numpy as np
import sys
import gc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from openpyxl) (2.0.0)

Carregando as bases de dados:

In [24]:
gc.collect()
colunas = [
    "ID_SAEB",
    "IN_PUBLICA",
    "ID_LOCALIZACAO",
    "IN_PROFICIENCIA_MT",
    "PROFICIENCIA_MT_SAEB",
    "TX_RESP_Q01",
    "TX_RESP_Q04",
    "TX_RESP_Q07",
    "TX_RESP_Q09b",
    "TX_RESP_Q11c",
    "TX_RESP_Q11g",
    "TX_RESP_Q12i",
    "TX_RESP_Q16",
    "TX_RESP_Q18",
    "TX_RESP_Q20a",
    "TX_RESP_Q20c",
    "TX_RESP_Q21"    
]
df_saeb_2021 = pd.read_csv("2021/TS_ALUNO_9EF.csv",  usecols=colunas, encoding='latin-1', sep=";", dtype=str)

In [25]:
gc.collect()
colunas = [
    "ID_SAEB",
    "IN_PUBLICA",
    "ID_LOCALIZACAO",
    "IN_PROFICIENCIA_MT",
    "PROFICIENCIA_MT_SAEB",
    "TX_RESP_Q01",
    "TX_RESP_Q04",    
    "TX_RESP_Q08", 
    "TX_RESP_Q10b",
    "TX_RESP_Q12b",
    "TX_RESP_Q12f",
    "TX_RESP_Q13i",
    "TX_RESP_Q17",   
    "TX_RESP_Q19",
    "TX_RESP_Q21a",
    "TX_RESP_Q21c",
    "TX_RESP_Q24"    
]
df_saeb_2023 = pd.read_csv("2023/TS_ALUNO_9EF.csv",  usecols=colunas, encoding='latin-1', sep=";", dtype=str)

#### 2. Remoção de dados que não são objetos do estudo
Como o objetivo do estudo é analisar o desempenho em matemática dos alunos de escolas públicas, serão selecionados apenas os dados desses alunos (a variável IN_PUBLICA é responsável por carregar essa informação). Dentro desse conjunto, é necessário avaliar a participação de cada aluno, e se ele cumpriu o requisito mínimo necessário para ter seu desempenho avaliado (a variável IN_PROFICIENCIA_MT, que é o indicador para cálculo da proficiência em Matemática - no mínimo três itens respondidos no caderno de provas de Língua Portuguesa e Matemática - engloba essas informações). 
Registros além desses não contribuem para as análises propostas, portanto, será aplicado um filtro para identificar e selecionar apenas os registros de interesse, garantindo que o dataset final contenha apenas participantes de escolas públicas que efetivamente tiveram seu desempenho avaliado.

##### 2021

In [26]:
df_saeb_2021 = df_saeb_2021[(df_saeb_2021['IN_PROFICIENCIA_MT'] == '1') & (df_saeb_2021['IN_PUBLICA'] == '1')].copy()
df_saeb_2021

,ID_SAEB,IN_PUBLICA,ID_LOCALIZACAO,IN_PROFICIENCIA_MT,PROFICIENCIA_MT_SAEB,TX_RESP_Q01,TX_RESP_Q04,TX_RESP_Q07,TX_RESP_Q09b,TX_RESP_Q11c,TX_RESP_Q11g,TX_RESP_Q12i,TX_RESP_Q16,TX_RESP_Q18,TX_RESP_Q20a,TX_RESP_Q20c,TX_RESP_Q21
0,2021,1,1,1,234.739479,A,A,D,B,A,A,B,A,A,C,D,C
1,2021,1,1,1,165.188854,A,C,F,C,B,A,A,B,C,B,D,B
4,2021,1,1,1,208.589694,B,A,B,B,C,.,B,C,.,B,A,C
5,2021,1,1,1,188.68638,B,C,F,A,A,B,A,B,B,C,B,C
6,2021,1,1,1,283.393079,B,D,F,B,A,A,A,C,A,B,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591699,2021,1,1,1,161.64243,A,C,C,B,A,A,A,B,A,C,C,C
2591701,2021,1,1,1,207.928823,A,C,D,B,.,D,B,B,A,.,.,C
2591702,2021,1,1,1,309.389104,B,C,D,C,B,B,B,C,A,C,B,C
2591704,2021,1,1,1,263.621671,A,A,D,.,.,.,.,C,A,B,B,D
2591705,2021,1,1,1,294.178175,B,A,F,B,C,B,B,B,A,C,B,C

##### 2023

In [27]:
df_saeb_2023 = df_saeb_2023[(df_saeb_2023['IN_PROFICIENCIA_MT'] == '1') & (df_saeb_2023['IN_PUBLICA'] == '1')].copy()
df_saeb_2023

,ID_SAEB,IN_PUBLICA,ID_LOCALIZACAO,IN_PROFICIENCIA_MT,PROFICIENCIA_MT_SAEB,TX_RESP_Q01,TX_RESP_Q04,TX_RESP_Q08,TX_RESP_Q10b,TX_RESP_Q12b,TX_RESP_Q12f,TX_RESP_Q13i,TX_RESP_Q17,TX_RESP_Q19,TX_RESP_Q21a,TX_RESP_Q21c,TX_RESP_Q24
0,2023,1,1,1,218.734766,A,C,D,B,B,B,B,C,A,A,D,B
3,2023,1,1,1,186.094318,B,B,F,.,.,.,.,C,A,.,.,A
7,2023,1,1,1,242.608224,B,C,B,.,A,B,A,B,B,B,D,A
9,2023,1,1,1,227.650431,A,.,B,A,B,B,A,B,B,B,C,C
11,2023,1,1,1,266.778246,B,C,D,C,B,C,B,B,A,B,D,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502898,2023,1,1,1,241.227963,A,C,F,B,D,B,B,C,A,C,B,C
2502900,2023,1,1,1,220.519967,A,A,F,B,B,A,B,C,A,B,B,D
2502902,2023,1,1,1,341.751041,A,A,D,C,A,B,B,C,A,B,A,C
2502903,2023,1,1,1,328.555589,A,C,E,C,C,B,B,A,A,C,D,C
2502905,2023,1,1,1,220.753374,B,B,F,B,B,A,B,.,A,B,B,C

#### 3. Padronização dos datasets
Após a etapa 1 descrita acima, foram mantidas somente as variáveis (colunas) comuns a todos os anos. No entanto, entre um ano e outro são observadas diferenças na ordem em que algumas colunas aparecem e na apresentação de algumas alternativas. Essas questões devem ser tratadas para que não comprometam as análises subsequentes.
O primeiro passo para ordenar as colunas é definir um padrão de nomes a ser seguido pelas colunas em todos os datasets:

In [28]:
colunas_padrao = ["ANO", "PUBLICA","LOCALIZACAO",
                  "PROFICIENCIA","PROFICIENCIA_SAEB","SEXO",
                  "COR/RACA","ESCOL_MAE","FREQUENCIA_CONVERSA","QTD_COMPUTADOR","QTD_CARRO","GARAGEM","IDADE_INTROD_ESC","REPROVACAO",
                  "TEMPO_TRAB_DOMES","TEMPO_ESTUDO","POS_EF"]

Na sequência, para cada dataset, são mapeados os nomes atuais para os nomes padrão, e renomeadas as colunas:

##### 2021:

In [29]:
mapa_df_2021 = {
    "ID_SAEB": "ANO",
    "IN_PUBLICA": "PUBLICA",
    "ID_LOCALIZACAO": "LOCALIZACAO",
    "IN_PROFICIENCIA_MT": "PROFICIENCIA",
    "PROFICIENCIA_MT_SAEB": "PROFICIENCIA_SAEB",
    "TX_RESP_Q01": "SEXO",
    "TX_RESP_Q04": "COR/RACA",
    "TX_RESP_Q07": "ESCOL_MAE",
    "TX_RESP_Q09b": "FREQUENCIA_CONVERSA",
    "TX_RESP_Q11c": "QTD_COMPUTADOR",
    "TX_RESP_Q11g": "QTD_CARRO",
    "TX_RESP_Q12i": "GARAGEM",
    "TX_RESP_Q16": "IDADE_INTROD_ESC",     
    "TX_RESP_Q18": "REPROVACAO",
    "TX_RESP_Q20a": "TEMPO_ESTUDO",
    "TX_RESP_Q20c": "TEMPO_TRAB_DOMES",
    "TX_RESP_Q21": "POS_EF",

}
df_saeb_2021 = df_saeb_2021.rename(columns=mapa_df_2021)

##### 2023:

In [30]:
mapa_df_2023 = {
    "ID_SAEB": "ANO",
    "IN_PUBLICA": "PUBLICA",
    "ID_LOCALIZACAO": "LOCALIZACAO",
    "IN_PROFICIENCIA_MT": "PROFICIENCIA",
    "PROFICIENCIA_MT_SAEB": "PROFICIENCIA_SAEB",
    "TX_RESP_Q01": "SEXO",
    "TX_RESP_Q04": "COR/RACA",
    "TX_RESP_Q08": "ESCOL_MAE",
    "TX_RESP_Q10b": "FREQUENCIA_CONVERSA",
    "TX_RESP_Q12b": "QTD_COMPUTADOR",
    "TX_RESP_Q12f": "QTD_CARRO",
    "TX_RESP_Q13i": "GARAGEM",
    "TX_RESP_Q17": "IDADE_INTROD_ESC",     
    "TX_RESP_Q19": "REPROVACAO",
    "TX_RESP_Q21a": "TEMPO_ESTUDO",
    "TX_RESP_Q21c": "TEMPO_TRAB_DOMES",
    "TX_RESP_Q24": "POS_EF",
  
}
df_saeb_2023 = df_saeb_2023.rename(columns=mapa_df_2023)

Por último, a ordem das colunas de todos os datasets é padronizada:

In [31]:
df_saeb_2021 = df_saeb_2021.reindex(columns=colunas_padrao)
df_saeb_2023 = df_saeb_2023.reindex(columns=colunas_padrao)

Agora, será realizada a padronização semântica das perguntas do questionário, para garantir que os significados das respostas sejam comparáveis entre os anos. O primeiro passo é criar uma “tabela de correspondência” (de-para) entre as alternativas de cada ano e um padrão único.
No caso em que hajam as opções "*", que representa "Nulo", e "." que representa "Branco", é importante decidir qual será o tratamento analítico dessas categorias, porque "Nulo" e "Branco" normalmente não representam uma resposta válida ao conteúdo da pergunta — representam ausência de resposta. 
A solução adotada foi criar uma categoria única "Não respondeu", que permite analisar taxa de não resposta.

As perguntas serão tratadas segundo o padrão de respostas.

Questão 1 - Qual é o seu sexo?

In [46]:
padrao_sexo = [
    "Não respondeu",
    "Masculino",
    "Feminino",
    "Não quis declarar"
]
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Masculino",
    "B": "Feminino",
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Masculino",
    "B": "Feminino",
    "C": "Não quis declarar"
}

df_saeb_2021["SEXO"] = df_saeb_2021["SEXO"].replace(mapa_2021)
df_saeb_2023["SEXO"] = df_saeb_2023["SEXO"].replace(mapa_2023)

Questão 2 - Qual é a sua cor ou raça?

In [33]:
padrao_cor = [
    "Não respondeu",
    "Branca",
    "Preta",
    "Parda",
    "Outra",
    "Não quis declarar"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Branca",
    "B": "Preta",
    "C": "Parda",
    "D": "Outra",
    "E": "Outra",
    "F": "Não quis declarar"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Branca",
    "B": "Preta",
    "C": "Parda",
    "D": "Outra",
    "E": "Outra",
    "F": "Não quis declarar"
}

df_saeb_2021["COR/RACA"] = df_saeb_2021["COR/RACA"].replace(mapa_2021)
df_saeb_2023["COR/RACA"] = df_saeb_2023["COR/RACA"].replace(mapa_2023)

Questão 3a - Normalmente, quem mora na sua casa? Mãe ou madrasta	

Questão 3b - Normalmente, quem mora na sua casa? Pai ou padrasto

Questão 3c - Normalmente, quem mora na sua casa? Outros

Questão 7a - Na região que você mora tem: Rua pavimentada

Questão 7b - Na região que você mora tem: Água tratada 

Questão 7c - Na região que você mora tem: Iluminação 

Questão 9a - Na sua casa tem: Tv a cabo

Questão 9b - Na sua casa tem: Rede Wi-Fi	

Questão 9c - Na sua casa tem: Um quarto só seu	

Questão 9d - Na sua casa tem: Mesa para estudar

Questão 9e - Na sua casa tem: Garagem

Questão 9f - Na sua casa tem: Forno de microondas

Questão 9g - Na sua casa tem: Aspirador de pó	

Questão 9h - Na sua casa tem: Máquina de lavar roupa	

Questão 9i - Na sua casa tem: Freezer 

Questão 14 - Você já foi reprovado?	

Questão 15 - Alguma vez você abandonou a escola deixando de frequentá-la até o final do ano escolar?

In [34]:
padrao_morador_itens_reprovacao_abandono = [
    "Não respondeu",
    "Não",
    "Sim"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não",
    "B": "Sim",
    "C": "Sim"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não",
    "B": "Sim",
    "C": "Sim"
}


df_saeb_2021["GARAGEM"] = df_saeb_2021["GARAGEM"].replace(mapa_2021)
df_saeb_2023["GARAGEM"] = df_saeb_2023["GARAGEM"].replace(mapa_2023)

df_saeb_2021["REPROVACAO"] = df_saeb_2021["REPROVACAO"].replace(mapa_2021)
df_saeb_2023["REPROVACAO"] = df_saeb_2023["REPROVACAO"].replace(mapa_2023)

Questão 4 - Qual é a maior escolaridade da sua mãe?	

Questão 5 -	Qual é a maior escolaridade de seu pai?

In [35]:
padrao_escolaridade = [
    "Não respondeu",
    "Fundamental incompleto",
    "Fundamental completo",
    "Médio completo",
    "Superior completo",
    "Não sabe"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Fundamental incompleto",
    "B": "Fundamental incompleto",
    "C": "Fundamental completo",
    "D": "Médio completo",
    "E": "Superior completo",
    "F": "Não sabe"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Fundamental incompleto",
    "B": "Fundamental incompleto",
    "C": "Fundamental completo",
    "D": "Médio completo",
    "E": "Superior completo",
    "F": "Não sabe"
}

df_saeb_2021["ESCOL_MAE"] = df_saeb_2021["ESCOL_MAE"].replace(mapa_2021)
df_saeb_2023["ESCOL_MAE"] = df_saeb_2023["ESCOL_MAE"].replace(mapa_2023)

Questão 6a - Com que frequência seus pais ou responsáveis costumam: Conversar com você sobre o que acontece na escola.	

Questão 6b - Com que frequência seus pais ou responsáveis costumam: Incentivar você a estudar.	

Questão 6c - Com que frequência seus pais ou responsáveis costumam: Incentivar você a fazer a tarefa de casa.	

Questão 6d - Com que frequência seus pais ou responsáveis costumam: Incentivar você a comparecer às aulas.	

Questão 6e - Com que frequência seus pais ou responsáveis costumam: Ir às reuniões de pais na escola.

In [36]:
padrao_freq = [
    "Não respondeu",
    "Nunca",
    "Às vezes",
    "Sempre"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Nunca",
    "B": "Às vezes",
    "C": "Sempre"
}

mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Nunca",
    "B": "Às vezes",
    "C": "Sempre"
}
df_saeb_2021["FREQUENCIA_CONVERSA"] = df_saeb_2021["FREQUENCIA_CONVERSA"].replace(mapa_2021)
df_saeb_2023["FREQUENCIA_CONVERSA"] = df_saeb_2023["FREQUENCIA_CONVERSA"].replace(mapa_2023)

Questão 8a - Dos itens relacionados abaixo, quantos existem na sua casa? Geladeira

Questão 8b - Dos itens relacionados abaixo, quantos existem na sua casa? Computador

Questão 8c - Dos itens relacionados abaixo, quantos existem na sua casa? Quartos para dormir

Questão 8d - Dos itens relacionados abaixo, quantos existem na sua casa? Televisão	

Questão 8e - Dos itens relacionados abaixo, quantos existem na sua casa? Banheiro

Questão 8f - Dos itens relacionados abaixo, quantos existem na sua casa? Carro

In [37]:
padrao_qtd = [
    "Não respondeu",
    "0",
    "1 ou 2",
    "3 ou mais"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "0",
    "B": "1 ou 2",
    "C": "1 ou 2",
    "D": "3 ou mais" 
}

mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "0",
    "B": "1 ou 2",
    "C": "1 ou 2",
    "D": "3 ou mais" 
}


df_saeb_2021["QTD_COMPUTADOR"] = df_saeb_2021["QTD_COMPUTADOR"].replace(mapa_2021)
df_saeb_2023["QTD_COMPUTADOR"] = df_saeb_2023["QTD_COMPUTADOR"].replace(mapa_2023)

df_saeb_2021["QTD_CARRO"] = df_saeb_2021["QTD_CARRO"].replace(mapa_2021)
df_saeb_2023["QTD_CARRO"] = df_saeb_2023["QTD_CARRO"].replace(mapa_2023)

Questão 12 - Com que idade você entrou na escola?

In [38]:
padrao_idade = [
    "Não respondeu",
    "3 ou menos",
    "Entre 4 e 7",
    "8 ou mais"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "3 ou menos",
    "B": "Entre 4 e 7",
    "C": "Entre 4 e 7",
    "D": "8 ou mais"
}

mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "3 ou menos",
    "B": "Entre 4 e 7",
    "C": "Entre 4 e 7",
    "D": "8 ou mais"
}

df_saeb_2021["IDADE_INTROD_ESC"] = df_saeb_2021["IDADE_INTROD_ESC"].replace(mapa_2021)
df_saeb_2023["IDADE_INTROD_ESC"] = df_saeb_2023["IDADE_INTROD_ESC"].replace(mapa_2023)

Questão 16a - Fora da escola em dias de aula, quanto tempo você usa para: Lazer

Questão 16b	- Fora da escola em dias de aula, quanto tempo você usa para: Fazer cursos

Questão 16c - Fora da escola em dias de aula, quanto tempo você usa para: Fazer trabalhos domésticos	

Questão 16d	- Fora da escola em dias de aula, quanto tempo você usa para: Estudar

Questão 16e - Fora da escola em dias de aula, quanto tempo você usa para: Trabalhar fora de casa

In [39]:
padrao_tempo_atividades = [
    "Não respondeu",
    "Não usa o tempo para isso",
    "Menos de 1 hora",
    "Entre 1 e 2 horas",
    "Mais de 2 horas"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não usa o tempo para isso",
    "B": "Menos de 1 hora",
    "C": "Entre 1 e 2 horas",
    "D": "Mais de 2 horas"
}

mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não usa o tempo para isso",
    "B": "Menos de 1 hora",
    "C": "Entre 1 e 2 horas",
    "D": "Mais de 2 horas"
}


df_saeb_2021["TEMPO_TRAB_DOMES"] = df_saeb_2021["TEMPO_TRAB_DOMES"].replace(mapa_2021)
df_saeb_2023["TEMPO_TRAB_DOMES"] = df_saeb_2023["TEMPO_TRAB_DOMES"].replace(mapa_2023)


df_saeb_2021["TEMPO_ESTUDO"] = df_saeb_2021["TEMPO_ESTUDO"].replace(mapa_2021)
df_saeb_2023["TEMPO_ESTUDO"] = df_saeb_2023["TEMPO_ESTUDO"].replace(mapa_2023)

Questão 17 - Quando terminar o Ensino Fundamental você pretende

In [40]:
padrao_pos = [
    "Não respondeu",
    "Somente estudar",
    "Somente trabalhar",
    "Estudar e trabalhar",
    "Não sabe"
]

mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Somente estudar",
    "B": "Somente trabalhar",
    "C": "Estudar e trabalhar",
    "D": "Não sabe"
}

mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Somente estudar",
    "B": "Somente trabalhar",
    "C": "Estudar e trabalhar",
    "D": "Não sabe"
}
df_saeb_2021["POS_EF"] = df_saeb_2021["POS_EF"].replace(mapa_2021)
df_saeb_2023["POS_EF"] = df_saeb_2023["POS_EF"].replace(mapa_2023)

#### 4. Unificação das bases dos diferentes anos
Realizar a união de bases de dados em uma análise multianual é fundamental para garantir uma visão mais completa, consistente e comparável ao longo do tempo. Isso permite unir as informações dos diferentes anos em uma única estrutura, facilitando sua exploração.

In [47]:
gc.collect()

df_unif = pd.concat([df_saeb_2021, df_saeb_2023], ignore_index=True)

df_unif = df_unif.copy()

numericas = [
    "ANO",
    "PUBLICA",
    "LOCALIZACAO",
    "PROFICIENCIA",
    "PROFICIENCIA_SAEB",  
]    
for col in numericas:
    df_unif[col] = pd.to_numeric(
    df_unif[col],
    errors="coerce"
)

categoricas = [
    "SEXO",
    "COR/RACA",
    "ESCOL_MAE",
    "FREQUENCIA_CONVERSA",
    "QTD_COMPUTADOR",
    "QTD_CARRO",
    "GARAGEM",
    "IDADE_INTROD_ESC",     
    "REPROVACAO",
    "TEMPO_TRAB_DOMES",
    "TEMPO_ESTUDO",
    "POS_EF"    
]
for col in categoricas:
    df_unif[col] = df_unif[col].astype("category")

processed_dir = r"C:\Users\emill\Downloads\TCC\processed"

os.makedirs(processed_dir, exist_ok=True)

out_path = os.path.join(processed_dir, "BASE_AED.parquet")

df_unif = pd.DataFrame(df_unif)
df_unif.reset_index(drop=True, inplace=True)

df_unif.to_parquet(out_path, index=False, engine="pyarrow")