Importando as bibliotecas e módulos necessários:

In [1]:
!pip install openpyxl
import os
import pandas as pd
import numpy as np
import sys
import gc

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from openpyxl) (2.0.0)

Carregando as bases de dados:

In [2]:
gc.collect
df_saeb_2019 = pd.read_csv("2019/TS_ALUNO_9EF.csv",  encoding='latin-1', sep=";", dtype=str)

In [3]:
gc.collect()
df_saeb_2021 = pd.read_csv("2021/TS_ALUNO_9EF.csv", encoding='latin-1', sep=";", dtype=str)

In [4]:
gc.collect()
df_saeb_2023 = pd.read_csv("2023/TS_ALUNO_9EF.csv",  encoding='latin-1', sep=";", dtype=str)

### Pré-processamento dos dados
Esta seção descreve o pré-processamento realizado nos dados antes de submetê-los à análise. São descritos as motivações e os processos relacionados à fusão de conjuntos e à limpeza de dados. 

#### 1. Filtro das colunas
Nessa etapa, serão retiradas de todos os datasets aquelas colunas que carregam informações que não precisam ser analisadas, ou seja, colunas consideradas desnecessárias aos objetivos do estudo. 

##### Variáveis referentes à avaliação:
Essas informações referem-se à estrutura e à aplicação da prova, não sendo essenciais para os objetivos deste trabalho, que não envolvem análise de participação, padrão de respostas, etc. Assim, optou-se por suas exclusões:

IN_PREENCHIMENTO_LP, IN_PREENCHIMENTO_MT, IN_PREENCHIMENTO_CH, IN_PREENCHIMENTO_CN (Indicadores de preenchimento da prova);

IN_PRESENCA_LP, IN_PRESENCA_MT, IN_PRESENCA_CH, IN_PRESENCA_CN (Indicadores de presença na prova);

ID_CADERNO_LP, ID_CADERNO_MT, ID_CADERNO_CH, ID_CADERNO_CN (Números dos cadernos de prova);

ID_BLOCO_1_LP, ID_BLOCO_2_LP, ID_BLOCO_1_MT, ID_BLOCO_2_MT, ID_BLOCO_1_CH, ID_BLOCO_2_CH, ID_BLOCO_3_CH, ID_BLOCO_1_CN, ID_BLOCO_2_CN, ID_BLOCO_3_CN (Identificadores dos blocos de prova);

NU_BLOCO_1_ABERTA_CH, NU_BLOCO_2_ABERTA_CH, NU_BLOCO_1_ABERTA_CN, NU_BLOCO_2_ABERTA_CN (Identificadores dos blocos de resposta construída da prova);  

TX_RESP_BLOCO1_LP, TX_RESP_BLOCO2_LP, TX_RESP_BLOCO1_MT, TX_RESP_BLOCO2_MT, TX_RESP_BLOCO1_CH, TX_RESP_BLOCO2_CH, TX_RESP_BLOCO3_CH, TX_RESP_BLOCO1_CN, TX_RESP_BLOCO2_CN, TX_RESP_BLOCO3_CN (Respostas do aluno a cada bloco da prova);

CO_CONCEITO_Q1_CH, CO_CONCEITO_Q2_CH, CO_CONCEITO_Q1_CN, CO_CONCEITO_Q2_CN (Conceitos obtidos nas questões de resposta construída);

IN_AMOSTRA (Indicador de participação da amostra)	

ESTRATO (Descrição dos estratos - Os estratos são compostos por características da participação da escola na avaliação e representam agrupamentos para os quais a avaliação fornece resultados confiáveis para Língua portuguesa e Matemática), ESTRATO_CIENCIAS (Descrição dos estratos para amostra de Ciências Humanas e Ciências da Natureza	- Os estratos são compostos por características da participação da escola na avaliação e representam agrupamentos para os quais a avaliação fornece resultados confiáveis para Ciências Humanas e Ciências da Natureza);

IN_PREENCHIMENTO_QUESTIONARIO (Indicador de preenchimento do questionário).

##### Variáveis referentes à proficiência em outras disciplinas:
Essas variáveis referem-se à proficiência em Língua Portuguesa, Ciências Humanas e Ciências da Natureza, ou seja, disciplinas que não são objeto do estudo.

IN_PROFICIENCIA_LP, IN_PROFICIENCIA_CH, IN_PROFICIENCIA_CN (Indicadores para cálculo da proficiência (no mínimo três itens respondidos no caderno de provas));	

PESO_ALUNO_LP, PESO_ALUNO_CH, PESO_ALUNO_CN (Peso do aluno na prova);

PROFICIENCIA_LP, PROFICIENCIA_CH, PROFICIENCIA_CN (Proficiência do aluno calculada na escala única do SAEB, com média = 0 e desvio = 1 na população de referência);

ERRO_PADRAO_LP, ERRO_PADRAO_CH, ERRO_PADRAO_CN (Erro padrão da proficiência);

PROFICIENCIA_LP_SAEB, PROFICIENCIA_CH_SAEB, PROFICIENCIA_CN_SAEB (Proficiência do aluno transformada na escala única do SAEB, com média = 250, desvio = 50(do SAEB/97));

ERRO_PADRAO_LP_SAEB, ERRO_PADRAO_CH_SAEB,  ERRO_PADRAO_CN_SAEB (Erro padrão da proficiência transformada).

##### Outras:
Os datasets dos diferentes anos possuem algumas variáveis diferentes entre si, portanto, algumas colunas devem ser desconsideradas por estarem presentes apenas na base de algum(ns) dos anos, o que comprometeria a consistência das análises multianuais.

IN_INSE (Indicador para cálculo do INSE (Indicador de Nível Socioeconômico));

INSE_ALUNO (Resultado individual do INSE para o aluno);

NU_TIPO_NIVEL_INSE (Classificação do Indicador de Nível Socioeconômico em 8 Grupos);

PESO_ALUNO_INSE (Peso do Aluno para cálculo do INSE).

##### Questionário:
Os datasets dos diferentes anos possuem algumas questões diferentes entre si, portanto, algumas colunas devem ser desconsideradas por estarem presentes apenas na base de algum(ns) dos anos, o que comprometeria a consistência das análises multianuais. 

Em 2019, serão removidas as seguintes questões (colunas) que diferem entre os anos: 
TX_RESP_Q003c, TX_RESP_Q003d, TX_RESP_Q007, TX_RESP_Q009b, TX_RESP_Q018a, TX_RESP_Q018b, TX_RESP_Q018c.

In [5]:
df_2019_red = df_saeb_2019.drop(columns=[
    'IN_PREENCHIMENTO_LP', 'IN_PREENCHIMENTO_MT', 'IN_PREENCHIMENTO_CH', 'IN_PREENCHIMENTO_CN', 'IN_PRESENCA_LP', 'IN_PRESENCA_MT', 'IN_PRESENCA_CH',
    'IN_PRESENCA_CN', 'ID_CADERNO_LP', 'ID_BLOCO_1_LP', 'ID_BLOCO_2_LP', 'ID_CADERNO_MT', 'ID_BLOCO_1_MT', 'ID_BLOCO_2_MT', 'ID_CADERNO_CH', 
    'ID_BLOCO_1_CH', 'ID_BLOCO_2_CH', 'ID_BLOCO_3_CH', 'NU_BLOCO_1_ABERTA_CH', 'NU_BLOCO_2_ABERTA_CH', 'ID_CADERNO_CN', 'ID_BLOCO_1_CN', 'ID_BLOCO_2_CN',
    'ID_BLOCO_3_CN', 'NU_BLOCO_1_ABERTA_CN', 'NU_BLOCO_2_ABERTA_CN', 'TX_RESP_BLOCO1_LP', 'TX_RESP_BLOCO2_LP', 'TX_RESP_BLOCO1_MT', 'TX_RESP_BLOCO2_MT',
    'TX_RESP_BLOCO1_CH', 'TX_RESP_BLOCO2_CH', 'TX_RESP_BLOCO3_CH', 'CO_CONCEITO_Q1_CH', 'CO_CONCEITO_Q2_CH', 'TX_RESP_BLOCO1_CN', 'TX_RESP_BLOCO2_CN', 
    'TX_RESP_BLOCO3_CN', 'CO_CONCEITO_Q1_CN', 'CO_CONCEITO_Q2_CN', 'IN_AMOSTRA', 'ESTRATO', 'ESTRATO_CIENCIAS', 'IN_PREENCHIMENTO_QUESTIONARIO',
    
    'IN_PROFICIENCIA_LP', 'IN_PROFICIENCIA_CH', 'IN_PROFICIENCIA_CN', 'PESO_ALUNO_LP', 'PROFICIENCIA_LP', 'ERRO_PADRAO_LP', 'PROFICIENCIA_LP_SAEB', 
    'ERRO_PADRAO_LP_SAEB', 'PESO_ALUNO_CH', 'PROFICIENCIA_CH', 'ERRO_PADRAO_CH', 'PROFICIENCIA_CH_SAEB', 'ERRO_PADRAO_CH_SAEB', 'PESO_ALUNO_CN', 
    'PROFICIENCIA_CN', 'ERRO_PADRAO_CN', 'PROFICIENCIA_CN_SAEB', 'ERRO_PADRAO_CN_SAEB', 
    
    'TX_RESP_Q003C', 'TX_RESP_Q003D', 'TX_RESP_Q007', 'TX_RESP_Q009B', 'TX_RESP_Q018A', 'TX_RESP_Q018B', 'TX_RESP_Q018C'
])
df_2019_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q013,TX_RESP_Q014,TX_RESP_Q015,TX_RESP_Q016,TX_RESP_Q017A,TX_RESP_Q017B,TX_RESP_Q017C,TX_RESP_Q017D,TX_RESP_Q017E,TX_RESP_Q019
0,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,B,A,D,A,D,B,A,C
1,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,B,A,C
2,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,C,A,D
3,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,D,C,A,D
4,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,*,B,A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2388926,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,.,.,.,.,.,.,.,.,.,.
2388927,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,C,A,A,D,B,C,D,A,A
2388928,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,A,B,A,D,A,A,C,A,C
2388929,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,C,A,B,A,D,A,B,B,A,B
2388930,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,.,.,.,.,.,.,.,.,.,.

Em 2021, serão removidas as seguintes questões (colunas) que diferem entre os anos: TX_RESP_Q01, TX_RESP_Q02, TX_RESP_Q05, TX_RESP_Q06c, TX_RESP_Q06d, TX_RESP_Q09a, TX_RESP_Q11b, TX_RESP_Q11h, TX_RESP_Q15, TX_RESP_Q22a, TX_RESP_Q22b, TX_RESP_Q22c, TX_RESP_Q22d, TX_RESP_Q22e, TX_RESP_Q22f, TX_RESP_Q22g, TX_RESP_Q22h, TX_RESP_Q22i.

In [6]:
df_2021_red = df_saeb_2021.drop(columns=[
    'IN_PREENCHIMENTO_LP', 'IN_PREENCHIMENTO_MT', 'IN_PREENCHIMENTO_CH', 'IN_PREENCHIMENTO_CN', 'IN_PRESENCA_LP', 'IN_PRESENCA_MT', 'IN_PRESENCA_CH',
    'IN_PRESENCA_CN', 'ID_CADERNO_LP', 'ID_BLOCO_1_LP', 'ID_BLOCO_2_LP', 'ID_CADERNO_MT', 'ID_BLOCO_1_MT', 'ID_BLOCO_2_MT', 'ID_CADERNO_CH', 
    'ID_BLOCO_1_CH', 'ID_BLOCO_2_CH', 'ID_BLOCO_3_CH', 'NU_BLOCO_1_ABERTA_CH', 'NU_BLOCO_2_ABERTA_CH', 'ID_CADERNO_CN', 'ID_BLOCO_1_CN', 'ID_BLOCO_2_CN',
    'ID_BLOCO_3_CN', 'NU_BLOCO_1_ABERTA_CN', 'NU_BLOCO_2_ABERTA_CN', 'TX_RESP_BLOCO1_LP', 'TX_RESP_BLOCO2_LP', 'TX_RESP_BLOCO1_MT', 'TX_RESP_BLOCO2_MT',
    'TX_RESP_BLOCO1_CH', 'TX_RESP_BLOCO2_CH', 'TX_RESP_BLOCO3_CH', 'CO_CONCEITO_Q1_CH', 'CO_CONCEITO_Q2_CH', 'TX_RESP_BLOCO1_CN', 'TX_RESP_BLOCO2_CN', 
    'TX_RESP_BLOCO3_CN', 'CO_CONCEITO_Q1_CN', 'CO_CONCEITO_Q2_CN', 'IN_AMOSTRA', 'ESTRATO', 'ESTRATO_CIENCIAS', 'IN_PREENCHIMENTO_QUESTIONARIO','IN_INSE', 
    'INSE_ALUNO', 'NU_TIPO_NIVEL_INSE', 'PESO_ALUNO_INSE',

    'IN_PROFICIENCIA_LP', 'IN_PROFICIENCIA_CH', 'IN_PROFICIENCIA_CN', 'PESO_ALUNO_LP', 'PROFICIENCIA_LP', 'ERRO_PADRAO_LP', 'PROFICIENCIA_LP_SAEB', 
    'ERRO_PADRAO_LP_SAEB', 'PESO_ALUNO_CH', 'PROFICIENCIA_CH', 'ERRO_PADRAO_CH', 'PROFICIENCIA_CH_SAEB', 'ERRO_PADRAO_CH_SAEB', 'PESO_ALUNO_CN', 
    'PROFICIENCIA_CN', 'ERRO_PADRAO_CN', 'PROFICIENCIA_CN_SAEB', 'ERRO_PADRAO_CN_SAEB', 
    
    'TX_RESP_Q01', 'TX_RESP_Q02', 'TX_RESP_Q05','TX_RESP_Q06c', 'TX_RESP_Q06d', 'TX_RESP_Q09a', 
    'TX_RESP_Q11b', 'TX_RESP_Q11h', 'TX_RESP_Q15', 'TX_RESP_Q22a', 'TX_RESP_Q22b', 'TX_RESP_Q22c', 'TX_RESP_Q22d', 'TX_RESP_Q22e', 'TX_RESP_Q22f', 
    'TX_RESP_Q22g', 'TX_RESP_Q22h', 'TX_RESP_Q22i'
])
df_2021_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q16,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20a,TX_RESP_Q20b,TX_RESP_Q20c,TX_RESP_Q20d,TX_RESP_Q20e,TX_RESP_Q21
0,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,A,A,A,A,C,B,D,D,B,C
1,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,B,C,C,A,B,D,D,D,C,B
2,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,.,.,.,.,.,.,.,.,.,.
3,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,.,.,.,.,.,.,.,.,.,.
4,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,A,.,A,B,*,A,A,D,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591932,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591933,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591934,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591935,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591936,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.

Em 2023, serão removidas as seguintes questões (colunas) que diferem entre os anos: TX_RESP_Q01, TX_RESP_Q02, TX_RESP_Q05a, TX_RESP_Q05b, TX_RESP_Q05c, TX_RESP_Q06, TX_RESP_Q07c, TX_RESP_Q07d, TX_RESP_Q10a, TX_RESP_Q12g, TX_RESP_Q15a, TX_RESP_Q15b, TX_RESP_Q22a, TX_RESP_Q22b, TX_RESP_Q22c, TX_RESP_Q22d, TX_RESP_Q22e, TX_RESP_Q22f, TX_RESP_Q22g, TX_RESP_Q22h, TX_RESP_Q23a, TX_RESP_Q23b, TX_RESP_Q23c, TX_RESP_Q23d, TX_RESP_Q23e, TX_RESP_Q23f, TX_RESP_Q23g, TX_RESP_Q23h, TX_RESP_Q23i.

In [7]:
df_2023_red = df_saeb_2023.drop(columns=[
    'IN_PREENCHIMENTO_LP', 'IN_PREENCHIMENTO_MT', 'IN_PREENCHIMENTO_CH', 'IN_PREENCHIMENTO_CN', 'IN_PRESENCA_LP', 'IN_PRESENCA_MT', 'IN_PRESENCA_CH',
    'IN_PRESENCA_CN', 'ID_CADERNO_LP', 'ID_BLOCO_1_LP', 'ID_BLOCO_2_LP', 'ID_CADERNO_MT', 'ID_BLOCO_1_MT', 'ID_BLOCO_2_MT', 'ID_CADERNO_CH', 
    'ID_BLOCO_1_CH', 'ID_BLOCO_2_CH', 'NU_BLOCO_1_ABERTA_CH', 'NU_BLOCO_2_ABERTA_CH', 'ID_CADERNO_CN', 'ID_BLOCO_1_CN', 'ID_BLOCO_2_CN',
    'ID_BLOCO_3_CN', 'NU_BLOCO_1_ABERTA_CN', 'NU_BLOCO_2_ABERTA_CN', 'TX_RESP_BLOCO1_LP', 'TX_RESP_BLOCO2_LP', 'TX_RESP_BLOCO1_MT', 'TX_RESP_BLOCO2_MT',
    'TX_RESP_BLOCO1_CH', 'TX_RESP_BLOCO2_CH', 'CO_CONCEITO_Q1_CH', 'CO_CONCEITO_Q2_CH', 'TX_RESP_BLOCO1_CN', 'TX_RESP_BLOCO2_CN', 
    'TX_RESP_BLOCO3_CN', 'CO_CONCEITO_Q1_CN', 'CO_CONCEITO_Q2_CN', 'IN_AMOSTRA', 'ESTRATO', 'ESTRATO_CIENCIAS', 'IN_PREENCHIMENTO_QUESTIONARIO',
    'IN_INSE', 'INSE_ALUNO', 'NU_TIPO_NIVEL_INSE', 'PESO_ALUNO_INSE', 
    
    'IN_PROFICIENCIA_LP', 'IN_PROFICIENCIA_CH', 'IN_PROFICIENCIA_CN', 'PESO_ALUNO_LP', 'PROFICIENCIA_LP', 'ERRO_PADRAO_LP', 'PROFICIENCIA_LP_SAEB', 
    'ERRO_PADRAO_LP_SAEB', 'PESO_ALUNO_CH', 'PROFICIENCIA_CH', 'ERRO_PADRAO_CH', 'PROFICIENCIA_CH_SAEB', 'ERRO_PADRAO_CH_SAEB', 'PESO_ALUNO_CN', 
    'PROFICIENCIA_CN', 'ERRO_PADRAO_CN', 'PROFICIENCIA_CN_SAEB', 'ERRO_PADRAO_CN_SAEB', 
    
    'TX_RESP_Q01', 'TX_RESP_Q02', 'TX_RESP_Q05a', 'TX_RESP_Q05b', 'TX_RESP_Q05c', 
    'TX_RESP_Q06', 'TX_RESP_Q07c', 'TX_RESP_Q07d', 'TX_RESP_Q10a', 'TX_RESP_Q12g', 'TX_RESP_Q15a', 'TX_RESP_Q15b', 'TX_RESP_Q22a', 'TX_RESP_Q22b', 
    'TX_RESP_Q22c', 'TX_RESP_Q22d', 'TX_RESP_Q22e', 'TX_RESP_Q22f', 'TX_RESP_Q22g', 'TX_RESP_Q22h', 'TX_RESP_Q23a', 'TX_RESP_Q23b', 'TX_RESP_Q23c', 
    'TX_RESP_Q23d', 'TX_RESP_Q23e', 'TX_RESP_Q23f', 'TX_RESP_Q23g', 'TX_RESP_Q23h', 'TX_RESP_Q23i'
])
df_2023_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20,TX_RESP_Q21a,TX_RESP_Q21b,TX_RESP_Q21c,TX_RESP_Q21d,TX_RESP_Q21e,TX_RESP_Q24
0,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,A,A,D,D,D,B
1,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,.,.,.,.,.,.,.,.,.,.
2,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,.,.,.,.,.,.,.,.,.,.
3,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,.,.,.,.,D,A
4,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,.,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502902,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,A,A,A,B,C,A,A,D,C
2502903,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,A,C,A,A,C,D,D,C,D,C
2502904,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,.,.,.,.,.,.,.,.
2502905,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,A,A,B,A,B,A,D,C
2502906,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,.,.,.,.,.,.,.,.

#### 2. Remoção de dados que não são objetos do estudo
Como o objetivo do estudo é analisar o desempenho em matemática dos alunos de escolas públicas, serão selecionados apenas os dados desses alunos (a variável IN_PUBLICA é responsável por carregar essa informação). Dentro desse conjunto, é necessário avaliar a participação de cada aluno, e se ele cumpriu o requisito mínimo necessário para ter seu desempenho avaliado (a variável IN_PROFICIENCIA_MT, que é o indicador para cálculo da proficiência em Matemática - no mínimo três itens respondidos no caderno de provas de Língua Portuguesa e Matemática - engloba essas informações). 
Registros além desses não contribuem para as análises propostas, portanto, será aplicado um filtro para identificar e selecionar apenas os registros de interesse, garantindo que o dataset final contenha apenas participantes de escolas públicas que efetivamente tiveram seu desempenho avaliado.

##### 2019

In [8]:
df_2019_red = df_2019_red[(df_2019_red['IN_PROFICIENCIA_MT'] == '1') & (df_2019_red['IN_PUBLICA'] == '1')].copy()
df_2019_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q013,TX_RESP_Q014,TX_RESP_Q015,TX_RESP_Q016,TX_RESP_Q017A,TX_RESP_Q017B,TX_RESP_Q017C,TX_RESP_Q017D,TX_RESP_Q017E,TX_RESP_Q019
0,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,B,A,D,A,D,B,A,C
1,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,B,A,C
2,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,C,A,D
3,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,D,C,A,D
4,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,*,B,A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2388923,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,B,A,B,A,D,B,*,B,A,C
2388924,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,A,C,A,D,A,B,B,B,A
2388927,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,C,A,A,D,B,C,D,A,A
2388928,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,A,B,A,D,A,A,C,A,C
2388929,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,C,A,B,A,D,A,B,B,A,B

##### 2021

In [9]:
df_2021_red = df_2021_red[(df_2021_red['IN_PROFICIENCIA_MT'] == '1') & (df_2021_red['IN_PUBLICA'] == '1')].copy()
df_2021_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q16,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20a,TX_RESP_Q20b,TX_RESP_Q20c,TX_RESP_Q20d,TX_RESP_Q20e,TX_RESP_Q21
0,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,A,A,A,A,C,B,D,D,B,C
1,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,B,C,C,A,B,D,D,D,C,B
4,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,A,.,A,B,*,A,A,D,C
5,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,B,A,B,A,C,*,B,B,B,C
6,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,A,A,A,B,B,C,D,D,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591699,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,B,A,A,A,C,A,C,D,C,C
2591701,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,B,A,A,A,.,.,.,.,.,C
2591702,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,C,A,A,A,C,B,B,A,D,C
2591704,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,C,A,A,A,B,D,B,A,D,D
2591705,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,B,A,A,A,C,A,B,D,C,C

##### 2023

In [10]:
df_2023_red = df_2023_red[(df_2023_red['IN_PROFICIENCIA_MT'] == '1') & (df_2023_red['IN_PUBLICA'] == '1')].copy()
df_2023_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20,TX_RESP_Q21a,TX_RESP_Q21b,TX_RESP_Q21c,TX_RESP_Q21d,TX_RESP_Q21e,TX_RESP_Q24
0,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,A,A,D,D,D,B
3,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,.,.,.,.,D,A
7,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,B,A,B,A,B,A,D,A,C,A
9,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,B,A,B,A,B,A,C,D,B,C
11,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,B,A,A,A,B,A,D,A,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502898,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,C,A,A,C,B,B,A,D,C
2502900,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,A,A,A,B,A,B,A,D,D
2502902,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,A,A,A,B,C,A,A,D,C
2502903,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,A,C,A,A,C,D,D,C,D,C
2502905,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,A,A,B,A,B,A,D,C

#### 3. Padronização dos datasets
Após a etapa 1 descrita acima, foram mantidas somente as variáveis (colunas) comuns a todos os anos. No entanto, entre um ano e outro são observadas diferenças na ordem em que algumas colunas aparecem e na apresentação de algumas alternativas. Essas questões devem ser tratadas para que não comprometam as análises subsequentes.
O primeiro passo para ordenar as colunas é definir um padrão de nomes a ser seguido pelas colunas em todos os datasets:

In [11]:
colunas_padrao = ["ANO","REGIAO","UF","MUNICIPIO","AREA","ID_ESCOLA","PUBLICA","LOCALIZACAO","ID_TURMA","SERIE","ID_ALUNO","SITUACAO_CENSO",
                  "PROFICIENCIA","PESO","PROFICIENCIA_MT","ERRO_PADRAO_MT","PROFICIENCIA_SAEB","ERRO_PADRAO_MT_SAEB","LINGUA_FALADA",
                  "COR_RACA","MORADOR_MAE","MORADOR_PAI","MORADOR_OUTROS","ESCOL_MAE","ESCOL_PAI","FREQUENCIA_CONVERSA","FREQUENCIA_INCENTIVO_ESTUDO",
                  "FREQUENCIA_INCENTIVO_TAREFA","FREQUENCIA_INCENTIVO_AULA","FREQUENCIA_REUNIOES","ASFALTO_CALCAMENTO","AGUA_TRATADA","ILUMINACAO",
                  "QTD_GELADEIRA","QTD_COMPUTADOR","QTD_QUARTO","QTD_TELEVISAO","QTD_BANHEIRO","QTD_CARRO","TV_A_CABO","WI-FI","QUARTO","MESA","GARAGEM",
                  "MICROONDAS","ASPIRADOR","MAQUINA","FREEZER","TEMPO_ATE_ESCOLA","LOCOMOCAO_ATE_ESCOLA","IDADE_INTROD_ESC","TIPO_ESCOLA","REPROVACAO",
                  "ABANDONO","TEMPO_LAZER","TEMPO_CURSOS","TEMPO_TRAB_DOMES","TEMPO_ESTUDO","TEMPO_TRABALHO","POS_EF"]

Na sequência, para cada dataset, são mapeados os nomes atuais para os nomes padrão, e renomeadas as colunas:

##### 2019:

In [12]:
mapa_df_2019_red = {
    "ID_SAEB": "ANO",
    "ID_REGIAO": "REGIAO",
    "ID_UF": "UF",
    "ID_MUNICIPIO": "MUNICIPIO",
    "ID_AREA": "AREA",
    "ID_ESCOLA": "ID_ESCOLA",
    "IN_PUBLICA": "PUBLICA",
    "ID_LOCALIZACAO": "LOCALIZACAO",
    "ID_TURMA": "ID_TURMA",
    "ID_SERIE": "SERIE",
    "ID_ALUNO": "ID_ALUNO",
    "IN_SITUACAO_CENSO": "SITUACAO_CENSO",
    "IN_PROFICIENCIA_MT": "PROFICIENCIA",
    "PESO_ALUNO_MT": "PESO",
    "PROFICIENCIA_MT": "PROFICIENCIA_MT",
    "ERRO_PADRAO_MT": "ERRO_PADRAO_MT",
    "PROFICIENCIA_MT_SAEB": "PROFICIENCIA_SAEB",
    "ERRO_PADRAO_MT_SAEB": "ERRO_PADRAO_MT_SAEB",    
    "TX_RESP_Q001": "LINGUA_FALADA",
    "TX_RESP_Q002": "COR_RACA",
    "TX_RESP_Q003A": "MORADOR_MAE",
    "TX_RESP_Q003B": "MORADOR_PAI",
    "TX_RESP_Q003E": "MORADOR_OUTROS",
    "TX_RESP_Q004": "ESCOL_MAE",
    "TX_RESP_Q005": "ESCOL_PAI",
    "TX_RESP_Q006A": "FREQUENCIA_CONVERSA",
    "TX_RESP_Q006B": "FREQUENCIA_INCENTIVO_ESTUDO",
    "TX_RESP_Q006C": "FREQUENCIA_INCENTIVO_TAREFA",
    "TX_RESP_Q006D": "FREQUENCIA_INCENTIVO_AULA",
    "TX_RESP_Q006E": "FREQUENCIA_REUNIOES",
    "TX_RESP_Q008A": "ASFALTO_CALCAMENTO",
    "TX_RESP_Q008B": "AGUA_TRATADA",
    "TX_RESP_Q008C": "ILUMINACAO",
    "TX_RESP_Q009A": "QTD_GELADEIRA",
    "TX_RESP_Q009C": "QTD_COMPUTADOR",
    "TX_RESP_Q009D": "QTD_QUARTO",
    "TX_RESP_Q009E": "QTD_TELEVISAO",
    "TX_RESP_Q009F": "QTD_BANHEIRO",
    "TX_RESP_Q009G": "QTD_CARRO",
    "TX_RESP_Q010A": "TV_A_CABO",
    "TX_RESP_Q010B": "WI-FI",
    "TX_RESP_Q010C": "QUARTO",
    "TX_RESP_Q010D": "MESA",
    "TX_RESP_Q010E": "GARAGEM",
    "TX_RESP_Q010F": "MICROONDAS",
    "TX_RESP_Q010G": "ASPIRADOR",
    "TX_RESP_Q010H": "MAQUINA",
    "TX_RESP_Q010I": "FREEZER",
    "TX_RESP_Q011": "TEMPO_ATE_ESCOLA",
    "TX_RESP_Q012": "LOCOMOCAO_ATE_ESCOLA",
    "TX_RESP_Q013": "IDADE_INTROD_ESC",     
    "TX_RESP_Q014": "TIPO_ESCOLA",
    "TX_RESP_Q015": "REPROVACAO",
    "TX_RESP_Q016": "ABANDONO",
    "TX_RESP_Q017A": "TEMPO_LAZER",
    "TX_RESP_Q017B": "TEMPO_CURSOS",
    "TX_RESP_Q017C": "TEMPO_TRAB_DOMES",
    "TX_RESP_Q017D": "TEMPO_ESTUDO",
    "TX_RESP_Q017E": "TEMPO_TRABALHO",
    "TX_RESP_Q019": "POS_EF",
}
df_2019_red = df_2019_red.rename(columns=mapa_df_2019_red)
#df_2019_red

##### 2021:

In [13]:
mapa_df_2021_red = {
    "ID_SAEB": "ANO",
    "ID_REGIAO": "REGIAO",
    "ID_UF": "UF",
    "ID_MUNICIPIO": "MUNICIPIO",
    "ID_AREA": "AREA",
    "ID_ESCOLA": "ID_ESCOLA",
    "IN_PUBLICA": "PUBLICA",
    "ID_LOCALIZACAO": "LOCALIZACAO",
    "ID_TURMA": "ID_TURMA",
    "ID_SERIE": "SERIE",
    "ID_ALUNO": "ID_ALUNO",
    "IN_SITUACAO_CENSO": "SITUACAO_CENSO",
    "IN_PROFICIENCIA_MT": "PROFICIENCIA",
    "PESO_ALUNO_MT": "PESO",
    "PROFICIENCIA_MT": "PROFICIENCIA_MT",
    "ERRO_PADRAO_MT": "ERRO_PADRAO_MT",
    "PROFICIENCIA_MT_SAEB": "PROFICIENCIA_SAEB",
    "ERRO_PADRAO_MT_SAEB": "ERRO_PADRAO_MT_SAEB",     
    "TX_RESP_Q03": "LINGUA_FALADA",
    "TX_RESP_Q04": "COR_RACA",
    "TX_RESP_Q06a": "MORADOR_MAE",
    "TX_RESP_Q06b": "MORADOR_PAI",
    "TX_RESP_Q06e": "MORADOR_OUTROS",    
    "TX_RESP_Q07": "ESCOL_MAE",
    "TX_RESP_Q08": "ESCOL_PAI",
    "TX_RESP_Q09b": "FREQUENCIA_CONVERSA",
    "TX_RESP_Q09c": "FREQUENCIA_INCENTIVO_ESTUDO",
    "TX_RESP_Q09d": "FREQUENCIA_INCENTIVO_TAREFA",
    "TX_RESP_Q09e": "FREQUENCIA_INCENTIVO_AULA",
    "TX_RESP_Q09f": "FREQUENCIA_REUNIOES",    
    "TX_RESP_Q10a": "ASFALTO_CALCAMENTO",
    "TX_RESP_Q10b": "AGUA_TRATADA",
    "TX_RESP_Q10c": "ILUMINACAO",
    "TX_RESP_Q11a": "QTD_GELADEIRA",
    "TX_RESP_Q11c": "QTD_COMPUTADOR",
    "TX_RESP_Q11d": "QTD_QUARTO",
    "TX_RESP_Q11e": "QTD_TELEVISAO",
    "TX_RESP_Q11f": "QTD_BANHEIRO",
    "TX_RESP_Q11g": "QTD_CARRO",
    "TX_RESP_Q12a": "TV_A_CABO",
    "TX_RESP_Q12b": "WI-FI",
    "TX_RESP_Q12c": "QUARTO",
    "TX_RESP_Q12d": "MESA",
    "TX_RESP_Q12e": "MICROONDAS",
    "TX_RESP_Q12f": "ASPIRADOR",
    "TX_RESP_Q12g": "MAQUINA",
    "TX_RESP_Q12h": "FREEZER",
    "TX_RESP_Q12i": "GARAGEM",
    "TX_RESP_Q13": "TEMPO_ATE_ESCOLA",
    "TX_RESP_Q14": "LOCOMOCAO_ATE_ESCOLA",
    "TX_RESP_Q16": "IDADE_INTROD_ESC",     
    "TX_RESP_Q17": "TIPO_ESCOLA",
    "TX_RESP_Q18": "REPROVACAO",
    "TX_RESP_Q19": "ABANDONO",   
    "TX_RESP_Q20a": "TEMPO_ESTUDO",
    "TX_RESP_Q20b": "TEMPO_CURSOS",
    "TX_RESP_Q20c": "TEMPO_TRAB_DOMES",
    "TX_RESP_Q20d": "TEMPO_TRABALHO",
    "TX_RESP_Q20e": "TEMPO_LAZER",
    "TX_RESP_Q21": "POS_EF",
}
df_2021_red = df_2021_red.rename(columns=mapa_df_2021_red)
#df_2021_red

##### 2023:

In [14]:
mapa_df_2023_red = {
    "ID_SAEB": "ANO",
    "ID_REGIAO": "REGIAO",
    "ID_UF": "UF",
    "ID_MUNICIPIO": "MUNICIPIO",
    "ID_AREA": "AREA",
    "ID_ESCOLA": "ID_ESCOLA",
    "IN_PUBLICA": "PUBLICA",
    "ID_LOCALIZACAO": "LOCALIZACAO",
    "ID_TURMA": "ID_TURMA",
    "ID_SERIE": "SERIE",
    "ID_ALUNO": "ID_ALUNO",
    "IN_SITUACAO_CENSO": "SITUACAO_CENSO",
    "IN_PROFICIENCIA_MT": "PROFICIENCIA",
    "PESO_ALUNO_MT": "PESO",
    "PROFICIENCIA_MT": "PROFICIENCIA_MT",
    "ERRO_PADRAO_MT": "ERRO_PADRAO_MT",
    "PROFICIENCIA_MT_SAEB": "PROFICIENCIA_SAEB",
    "ERRO_PADRAO_MT_SAEB": "ERRO_PADRAO_MT_SAEB",
    "TX_RESP_Q03": "LINGUA_FALADA",
    "TX_RESP_Q04": "COR_RACA",
    "TX_RESP_Q07a": "MORADOR_MAE",
    "TX_RESP_Q07b": "MORADOR_PAI",
    "TX_RESP_Q07e": "MORADOR_OUTROS",
    "TX_RESP_Q08": "ESCOL_MAE",
    "TX_RESP_Q09": "ESCOL_PAI",
    "TX_RESP_Q10b": "FREQUENCIA_CONVERSA",
    "TX_RESP_Q10c": "FREQUENCIA_INCENTIVO_ESTUDO",
    "TX_RESP_Q10d": "FREQUENCIA_INCENTIVO_TAREFA",
    "TX_RESP_Q10e": "FREQUENCIA_INCENTIVO_AULA",
    "TX_RESP_Q10f": "FREQUENCIA_REUNIOES", 
    "TX_RESP_Q11a": "ASFALTO_CALCAMENTO",
    "TX_RESP_Q11b": "AGUA_TRATADA",
    "TX_RESP_Q11c": "ILUMINACAO",
    "TX_RESP_Q12a": "QTD_GELADEIRA",
    "TX_RESP_Q12b": "QTD_COMPUTADOR",
    "TX_RESP_Q12c": "QTD_QUARTO",
    "TX_RESP_Q12d": "QTD_TELEVISAO",
    "TX_RESP_Q12e": "QTD_BANHEIRO",
    "TX_RESP_Q12f": "QTD_CARRO",
    "TX_RESP_Q13a": "TV_A_CABO",
    "TX_RESP_Q13b": "WI-FI",
    "TX_RESP_Q13c": "QUARTO",
    "TX_RESP_Q13d": "MESA",
    "TX_RESP_Q13e": "MICROONDAS",
    "TX_RESP_Q13f": "ASPIRADOR",
    "TX_RESP_Q13g": "MAQUINA",
    "TX_RESP_Q13h": "FREEZER",
    "TX_RESP_Q13i": "GARAGEM",
    "TX_RESP_Q14": "TEMPO_ATE_ESCOLA",
    "TX_RESP_Q16": "LOCOMOCAO_ATE_ESCOLA",
    "TX_RESP_Q17": "IDADE_INTROD_ESC",     
    "TX_RESP_Q18": "TIPO_ESCOLA",
    "TX_RESP_Q19": "REPROVACAO",
    "TX_RESP_Q20": "ABANDONO",   
    "TX_RESP_Q21a": "TEMPO_ESTUDO",
    "TX_RESP_Q21b": "TEMPO_CURSOS",
    "TX_RESP_Q21c": "TEMPO_TRAB_DOMES",
    "TX_RESP_Q21d": "TEMPO_TRABALHO",
    "TX_RESP_Q21e": "TEMPO_LAZER",
    "TX_RESP_Q24": "POS_EF",
}
df_2023_red = df_2023_red.rename(columns=mapa_df_2023_red)
#df_2023_red

Por último, a ordem das colunas de todos os datasets é padronizada:

In [15]:
df_2019_red = df_2019_red.reindex(columns=colunas_padrao)
df_2021_red = df_2021_red.reindex(columns=colunas_padrao)
df_2023_red = df_2023_red.reindex(columns=colunas_padrao)

Agora, será realizada a padronização semântica das perguntas do questionário, para garantir que os significados das respostas sejam comparáveis entre os anos. O primeiro passo é criar uma “tabela de correspondência” (de-para) entre as alternativas de cada ano e um padrão único.
No caso em que hajam as opções "*", que representa "Nulo", e "." que representa "Branco", é importante decidir qual será o tratamento analítico dessas categorias, porque "Nulo" e "Branco" normalmente não representam uma resposta válida ao conteúdo da pergunta — representam ausência de resposta. 
A solução adotada foi criar uma categoria única "Não respondeu", que permite analisar taxa de não resposta.

As perguntas serão tratadas segundo o padrão de respostas.

Questão 1 - Qual língua você/seus pais fala(m) com mais frequência em sua casa?

In [16]:
padrao_lingua = [
    "Não respondeu",
    "Português",
    "Espanhol",
    "Outra"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Português",
    "B": "Espanhol",
    "C": "Outra"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Português",
    "B": "Espanhol",
    "C": "Outra"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Português",
    "B": "Espanhol",
    "C": "Outra",  
    "D": "Outra"
}
df_2019_red["LINGUA_FALADA"] = df_2019_red["LINGUA_FALADA"].replace(mapa_2019)
df_2021_red["LINGUA_FALADA"] = df_2021_red["LINGUA_FALADA"].replace(mapa_2021)
df_2023_red["LINGUA_FALADA"] = df_2023_red["LINGUA_FALADA"].replace(mapa_2023)

#set(df_2019_red["LINGUA_FALADA"].unique()) - set(padrao_lingua)
#set(df_2021_red["LINGUA_FALADA"].unique()) - set(padrao_lingua)
#set(df_2023_red["LINGUA_FALADA"].unique()) - set(padrao_lingua)

Questão 2 - Qual é a sua cor ou raça?

In [17]:
padrao_cor = [
    "Não respondeu",
    "Branca",
    "Preta",
    "Parda",
    "Outra",
    "Não quis declarar"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Branca",
    "B": "Preta",
    "C": "Parda",
    "D": "Outra",
    "E": "Outra",
    "F": "Não quis declarar"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Branca",
    "B": "Preta",
    "C": "Parda",
    "D": "Outra",
    "E": "Outra",
    "F": "Não quis declarar"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Branca",
    "B": "Preta",
    "C": "Parda",
    "D": "Outra",
    "E": "Outra",
    "F": "Não quis declarar"
}
df_2019_red["COR_RACA"] = df_2019_red["COR_RACA"].replace(mapa_2019)
df_2021_red["COR_RACA"] = df_2021_red["COR_RACA"].replace(mapa_2021)
df_2023_red["COR_RACA"] = df_2023_red["COR_RACA"].replace(mapa_2023)

#set(df_2019_red["COR/RACA"].unique()) - set(padrao_cor)
#set(df_2021_red["COR/RACA"].unique()) - set(padrao_cor)
#set(df_2023_red["COR/RACA"].unique()) - set(padrao_cor)

Questão 3a - Normalmente, quem mora na sua casa? Mãe ou madrasta	

Questão 3b - Normalmente, quem mora na sua casa? Pai ou padrasto

Questão 3c - Normalmente, quem mora na sua casa? Outros

Questão 7a - Na região que você mora tem: Rua pavimentada

Questão 7b - Na região que você mora tem: Água tratada 

Questão 7c - Na região que você mora tem: Iluminação 

Questão 9a - Na sua casa tem: Tv a cabo

Questão 9b - Na sua casa tem: Rede Wi-Fi	

Questão 9c - Na sua casa tem: Um quarto só seu	

Questão 9d - Na sua casa tem: Mesa para estudar

Questão 9e - Na sua casa tem: Garagem

Questão 9f - Na sua casa tem: Forno de microondas

Questão 9g - Na sua casa tem: Aspirador de pó	

Questão 9h - Na sua casa tem: Máquina de lavar roupa	

Questão 9i - Na sua casa tem: Freezer 

Questão 14 - Você já foi reprovado?	

Questão 15 - Alguma vez você abandonou a escola deixando de frequentá-la até o final do ano escolar?

In [18]:
padrao_morador_itens_reprovacao_abandono = [
    "Não respondeu",
    "Não",
    "Sim"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não",
    "B": "Sim",
    "C": "Sim"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não",
    "B": "Sim",
    "C": "Sim"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não",
    "B": "Sim",
    "C": "Sim"
}
df_2019_red["MORADOR_MAE"] = df_2019_red["MORADOR_MAE"].replace(mapa_2019)
df_2021_red["MORADOR_MAE"] = df_2021_red["MORADOR_MAE"].replace(mapa_2021)
df_2023_red["MORADOR_MAE"] = df_2023_red["MORADOR_MAE"].replace(mapa_2023)

df_2019_red["MORADOR_PAI"] = df_2019_red["MORADOR_PAI"].replace(mapa_2019)
df_2021_red["MORADOR_PAI"] = df_2021_red["MORADOR_PAI"].replace(mapa_2021)
df_2023_red["MORADOR_PAI"] = df_2023_red["MORADOR_PAI"].replace(mapa_2023)

df_2019_red["MORADOR_OUTROS"] = df_2019_red["MORADOR_OUTROS"].replace(mapa_2019)
df_2021_red["MORADOR_OUTROS"] = df_2021_red["MORADOR_OUTROS"].replace(mapa_2021)
df_2023_red["MORADOR_OUTROS"] = df_2023_red["MORADOR_OUTROS"].replace(mapa_2023)

df_2019_red["ASFALTO_CALCAMENTO"] = df_2019_red["ASFALTO_CALCAMENTO"].replace(mapa_2019)
df_2021_red["ASFALTO_CALCAMENTO"] = df_2021_red["ASFALTO_CALCAMENTO"].replace(mapa_2021)
df_2023_red["ASFALTO_CALCAMENTO"] = df_2023_red["ASFALTO_CALCAMENTO"].replace(mapa_2023)

df_2019_red["AGUA_TRATADA"] = df_2019_red["AGUA_TRATADA"].replace(mapa_2019)
df_2021_red["AGUA_TRATADA"] = df_2021_red["AGUA_TRATADA"].replace(mapa_2021)
df_2023_red["AGUA_TRATADA"] = df_2023_red["AGUA_TRATADA"].replace(mapa_2023)

df_2019_red["ILUMINACAO"] = df_2019_red["ILUMINACAO"].replace(mapa_2019)
df_2021_red["ILUMINACAO"] = df_2021_red["ILUMINACAO"].replace(mapa_2021)
df_2023_red["ILUMINACAO"] = df_2023_red["ILUMINACAO"].replace(mapa_2023)

df_2019_red["TV_A_CABO"] = df_2019_red["TV_A_CABO"].replace(mapa_2019)
df_2021_red["TV_A_CABO"] = df_2021_red["TV_A_CABO"].replace(mapa_2021)
df_2023_red["TV_A_CABO"] = df_2023_red["TV_A_CABO"].replace(mapa_2023)

df_2019_red["WI-FI"] = df_2019_red["WI-FI"].replace(mapa_2019)
df_2021_red["WI-FI"] = df_2021_red["WI-FI"].replace(mapa_2021)
df_2023_red["WI-FI"] = df_2023_red["WI-FI"].replace(mapa_2023)

df_2019_red["QUARTO"] = df_2019_red["QUARTO"].replace(mapa_2019)
df_2021_red["QUARTO"] = df_2021_red["QUARTO"].replace(mapa_2021)
df_2023_red["QUARTO"] = df_2023_red["QUARTO"].replace(mapa_2023)

df_2019_red["MESA"] = df_2019_red["MESA"].replace(mapa_2019)
df_2021_red["MESA"] = df_2021_red["MESA"].replace(mapa_2021)
df_2023_red["MESA"] = df_2023_red["MESA"].replace(mapa_2023)

df_2019_red["GARAGEM"] = df_2019_red["GARAGEM"].replace(mapa_2019)
df_2021_red["GARAGEM"] = df_2021_red["GARAGEM"].replace(mapa_2021)
df_2023_red["GARAGEM"] = df_2023_red["GARAGEM"].replace(mapa_2023)

df_2019_red["MICROONDAS"] = df_2019_red["MICROONDAS"].replace(mapa_2019)
df_2021_red["MICROONDAS"] = df_2021_red["MICROONDAS"].replace(mapa_2021)
df_2023_red["MICROONDAS"] = df_2023_red["MICROONDAS"].replace(mapa_2023)

df_2019_red["ASPIRADOR"] = df_2019_red["ASPIRADOR"].replace(mapa_2019)
df_2021_red["ASPIRADOR"] = df_2021_red["ASPIRADOR"].replace(mapa_2021)
df_2023_red["ASPIRADOR"] = df_2023_red["ASPIRADOR"].replace(mapa_2023)

df_2019_red["MAQUINA"] = df_2019_red["MAQUINA"].replace(mapa_2019)
df_2021_red["MAQUINA"] = df_2021_red["MAQUINA"].replace(mapa_2021)
df_2023_red["MAQUINA"] = df_2023_red["MAQUINA"].replace(mapa_2023)

df_2019_red["FREEZER"] = df_2019_red["FREEZER"].replace(mapa_2019)
df_2021_red["FREEZER"] = df_2021_red["FREEZER"].replace(mapa_2021)
df_2023_red["FREEZER"] = df_2023_red["FREEZER"].replace(mapa_2023)

df_2019_red["REPROVACAO"] = df_2019_red["REPROVACAO"].replace(mapa_2019)
df_2021_red["REPROVACAO"] = df_2021_red["REPROVACAO"].replace(mapa_2021)
df_2023_red["REPROVACAO"] = df_2023_red["REPROVACAO"].replace(mapa_2023)

df_2019_red["ABANDONO"] = df_2019_red["ABANDONO"].replace(mapa_2019)
df_2021_red["ABANDONO"] = df_2021_red["ABANDONO"].replace(mapa_2021)
df_2023_red["ABANDONO"] = df_2023_red["ABANDONO"].replace(mapa_2023)

Questão 4 - Qual é a maior escolaridade da sua mãe?	

Questão 5 -	Qual é a maior escolaridade de seu pai?

In [19]:
padrao_escolaridade = [
    "Não respondeu",
    "Fundamental incompleto",
    "Fundamental completo",
    "Médio completo",
    "Superior completo",
    "Não sabe"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Fundamental incompleto",
    "B": "Fundamental incompleto",
    "C": "Fundamental completo",
    "D": "Médio completo",
    "E": "Superior completo",
    "F": "Não sabe"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Fundamental incompleto",
    "B": "Fundamental incompleto",
    "C": "Fundamental completo",
    "D": "Médio completo",
    "E": "Superior completo",
    "F": "Não sabe"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Fundamental incompleto",
    "B": "Fundamental incompleto",
    "C": "Fundamental completo",
    "D": "Médio completo",
    "E": "Superior completo",
    "F": "Não sabe"
}
df_2019_red["ESCOL_MAE"] = df_2019_red["ESCOL_MAE"].replace(mapa_2019)
df_2021_red["ESCOL_MAE"] = df_2021_red["ESCOL_MAE"].replace(mapa_2021)
df_2023_red["ESCOL_MAE"] = df_2023_red["ESCOL_MAE"].replace(mapa_2023)

df_2019_red["ESCOL_PAI"] = df_2019_red["ESCOL_PAI"].replace(mapa_2019)
df_2021_red["ESCOL_PAI"] = df_2021_red["ESCOL_PAI"].replace(mapa_2021)
df_2023_red["ESCOL_PAI"] = df_2023_red["ESCOL_PAI"].replace(mapa_2023)

#set(df_2019_red["ESCOL_PAI"].unique()) - set(padrao_escolaridade)
#set(df_2021_red["ESCOL_PAI"].unique()) - set(padrao_escolaridade)
#set(df_2023_red["ESCOL_PAI"].unique()) - set(padrao_escolaridade)

Questão 6a - Com que frequência seus pais ou responsáveis costumam: Conversar com você sobre o que acontece na escola.	

Questão 6b - Com que frequência seus pais ou responsáveis costumam: Incentivar você a estudar.	

Questão 6c - Com que frequência seus pais ou responsáveis costumam: Incentivar você a fazer a tarefa de casa.	

Questão 6d - Com que frequência seus pais ou responsáveis costumam: Incentivar você a comparecer às aulas.	

Questão 6e - Com que frequência seus pais ou responsáveis costumam: Ir às reuniões de pais na escola.

In [20]:
padrao_freq = [
    "Não respondeu",
    "Nunca",
    "Às vezes",
    "Sempre"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Nunca",
    "B": "Às vezes",
    "C": "Sempre"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Nunca",
    "B": "Às vezes",
    "C": "Sempre"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Nunca",
    "B": "Às vezes",
    "C": "Sempre"
}
df_2019_red["FREQUENCIA_CONVERSA"] = df_2019_red["FREQUENCIA_CONVERSA"].replace(mapa_2019)
df_2021_red["FREQUENCIA_CONVERSA"] = df_2021_red["FREQUENCIA_CONVERSA"].replace(mapa_2021)
df_2023_red["FREQUENCIA_CONVERSA"] = df_2023_red["FREQUENCIA_CONVERSA"].replace(mapa_2023)

df_2019_red["FREQUENCIA_INCENTIVO_ESTUDO"] = df_2019_red["FREQUENCIA_INCENTIVO_ESTUDO"].replace(mapa_2019)
df_2021_red["FREQUENCIA_INCENTIVO_ESTUDO"] = df_2021_red["FREQUENCIA_INCENTIVO_ESTUDO"].replace(mapa_2021)
df_2023_red["FREQUENCIA_INCENTIVO_ESTUDO"] = df_2023_red["FREQUENCIA_INCENTIVO_ESTUDO"].replace(mapa_2023)

df_2019_red["FREQUENCIA_INCENTIVO_TAREFA"] = df_2019_red["FREQUENCIA_INCENTIVO_TAREFA"].replace(mapa_2019)
df_2021_red["FREQUENCIA_INCENTIVO_TAREFA"] = df_2021_red["FREQUENCIA_INCENTIVO_TAREFA"].replace(mapa_2021)
df_2023_red["FREQUENCIA_INCENTIVO_TAREFA"] = df_2023_red["FREQUENCIA_INCENTIVO_TAREFA"].replace(mapa_2023)

df_2019_red["FREQUENCIA_INCENTIVO_AULA"] = df_2019_red["FREQUENCIA_INCENTIVO_AULA"].replace(mapa_2019)
df_2021_red["FREQUENCIA_INCENTIVO_AULA"] = df_2021_red["FREQUENCIA_INCENTIVO_AULA"].replace(mapa_2021)
df_2023_red["FREQUENCIA_INCENTIVO_AULA"] = df_2023_red["FREQUENCIA_INCENTIVO_AULA"].replace(mapa_2023)

df_2019_red["FREQUENCIA_REUNIOES"] = df_2019_red["FREQUENCIA_REUNIOES"].replace(mapa_2019)
df_2021_red["FREQUENCIA_REUNIOES"] = df_2021_red["FREQUENCIA_REUNIOES"].replace(mapa_2021)
df_2023_red["FREQUENCIA_REUNIOES"] = df_2023_red["FREQUENCIA_REUNIOES"].replace(mapa_2023)

Questão 8a - Dos itens relacionados abaixo, quantos existem na sua casa? Geladeira

Questão 8b - Dos itens relacionados abaixo, quantos existem na sua casa? Computador

Questão 8c - Dos itens relacionados abaixo, quantos existem na sua casa? Quartos para dormir

Questão 8d - Dos itens relacionados abaixo, quantos existem na sua casa? Televisão	

Questão 8e - Dos itens relacionados abaixo, quantos existem na sua casa? Banheiro

Questão 8f - Dos itens relacionados abaixo, quantos existem na sua casa? Carro

In [21]:
padrao_qtd = [
    "Não respondeu",
    "0",
    "1 ou 2",
    "3 ou mais"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "0",
    "B": "1 ou 2",
    "C": "1 ou 2",
    "D": "3 ou mais" 
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "0",
    "B": "1 ou 2",
    "C": "1 ou 2",
    "D": "3 ou mais" 
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "0",
    "B": "1 ou 2",
    "C": "1 ou 2",
    "D": "3 ou mais" 
}
df_2019_red["QTD_GELADEIRA"] = df_2019_red["QTD_GELADEIRA"].replace(mapa_2019)
df_2021_red["QTD_GELADEIRA"] = df_2021_red["QTD_GELADEIRA"].replace(mapa_2021)
df_2023_red["QTD_GELADEIRA"] = df_2023_red["QTD_GELADEIRA"].replace(mapa_2023)

df_2019_red["QTD_COMPUTADOR"] = df_2019_red["QTD_COMPUTADOR"].replace(mapa_2019)
df_2021_red["QTD_COMPUTADOR"] = df_2021_red["QTD_COMPUTADOR"].replace(mapa_2021)
df_2023_red["QTD_COMPUTADOR"] = df_2023_red["QTD_COMPUTADOR"].replace(mapa_2023)

df_2019_red["QTD_QUARTO"] = df_2019_red["QTD_QUARTO"].replace(mapa_2019)
df_2021_red["QTD_QUARTO"] = df_2021_red["QTD_QUARTO"].replace(mapa_2021)
df_2023_red["QTD_QUARTO"] = df_2023_red["QTD_QUARTO"].replace(mapa_2023)

df_2019_red["QTD_TELEVISAO"] = df_2019_red["QTD_TELEVISAO"].replace(mapa_2019)
df_2021_red["QTD_TELEVISAO"] = df_2021_red["QTD_TELEVISAO"].replace(mapa_2021)
df_2023_red["QTD_TELEVISAO"] = df_2023_red["QTD_TELEVISAO"].replace(mapa_2023)

df_2019_red["QTD_BANHEIRO"] = df_2019_red["QTD_BANHEIRO"].replace(mapa_2019)
df_2021_red["QTD_BANHEIRO"] = df_2021_red["QTD_BANHEIRO"].replace(mapa_2021)
df_2023_red["QTD_BANHEIRO"] = df_2023_red["QTD_BANHEIRO"].replace(mapa_2023)

df_2019_red["QTD_CARRO"] = df_2019_red["QTD_CARRO"].replace(mapa_2019)
df_2021_red["QTD_CARRO"] = df_2021_red["QTD_CARRO"].replace(mapa_2021)
df_2023_red["QTD_CARRO"] = df_2023_red["QTD_CARRO"].replace(mapa_2023)

Questão 10 - Quanto tempo você demora para chegar à sua escola?

In [22]:
padrao_tempo_locomocao = [
    "Não respondeu",
    "Menos de 30 minutos",
    "Entre 30 minutos e 1 hora",
    "Mais de 1 hora"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Menos de 30 minutos",
    "B": "Entre 30 minutos e 1 hora",
    "C": "Mais de 1 hora"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Menos de 30 minutos",
    "B": "Entre 30 minutos e 1 hora",
    "C": "Mais de 1 hora"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Menos de 30 minutos",
    "B": "Entre 30 minutos e 1 hora",
    "C": "Mais de 1 hora"
}
df_2019_red["TEMPO_ATE_ESCOLA"] = df_2019_red["TEMPO_ATE_ESCOLA"].replace(mapa_2019)
df_2021_red["TEMPO_ATE_ESCOLA"] = df_2021_red["TEMPO_ATE_ESCOLA"].replace(mapa_2021)
df_2023_red["TEMPO_ATE_ESCOLA"] = df_2023_red["TEMPO_ATE_ESCOLA"].replace(mapa_2023)

set(df_2019_red["TEMPO_ATE_ESCOLA"].unique()) - set(padrao_tempo_locomocao)
set(df_2021_red["TEMPO_ATE_ESCOLA"].unique()) - set(padrao_tempo_locomocao)
set(df_2023_red["TEMPO_ATE_ESCOLA"].unique()) - set(padrao_tempo_locomocao)

set()

Questão 11 - Considerando a maior distância percorrida, normalmente de que forma você chega à sua escola?

In [23]:
padrao_locomocao = [
    "Não respondeu",
    "A pé",
    "De ônibus ou metrô",
    "De transporte escolar",
    "De carro ou moto",
    "Outro"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "A pé",
    "B": "De ônibus ou metrô",
    "C": "De transporte escolar",
    "D": "Outro",
    "E": "Outro",
    "F": "De carro ou moto",
    "G": "Outro"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "A pé",
    "B": "Outro",
    "C": "De transporte escolar",
    "D": "De ônibus ou metrô",
    "E": "De ônibus ou metrô",
    "F": "De carro ou moto",
    "G": "Outro"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "A pé",
    "B": "Outro",
    "C": "De transporte escolar",
    "D": "De ônibus ou metrô",
    "E": "De ônibus ou metrô",
    "F": "De carro ou moto",
    "G": "Outro",
    "H": "De carro ou moto",
    "I": "Outro"
}
df_2019_red["LOCOMOCAO_ATE_ESCOLA"] = df_2019_red["LOCOMOCAO_ATE_ESCOLA"].replace(mapa_2019)
df_2021_red["LOCOMOCAO_ATE_ESCOLA"] = df_2021_red["LOCOMOCAO_ATE_ESCOLA"].replace(mapa_2021)
df_2023_red["LOCOMOCAO_ATE_ESCOLA"] = df_2023_red["LOCOMOCAO_ATE_ESCOLA"].replace(mapa_2023)

#set(df_2019_red["LOCOMOCAO_ATE_ESCOLA"].unique()) - set(padrao_locomocao)
#set(df_2021_red["LOCOMOCAO_ATE_ESCOLA"].unique()) - set(padrao_locomocao)
#set(df_2023_red["LOCOMOCAO_ATE_ESCOLA"].unique()) - set(padrao_locomocao)

Questão 12 - Com que idade você entrou na escola?

In [24]:
padrao_idade = [
    "Não respondeu",
    "3 ou menos",
    "Entre 4 e 7",
    "8 ou mais"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "3 ou menos",
    "B": "Entre 4 e 7",
    "C": "Entre 4 e 7",
    "D": "8 ou mais"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "3 ou menos",
    "B": "Entre 4 e 7",
    "C": "Entre 4 e 7",
    "D": "8 ou mais"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "3 ou menos",
    "B": "Entre 4 e 7",
    "C": "Entre 4 e 7",
    "D": "8 ou mais"
}
df_2019_red["IDADE_INTROD_ESC"] = df_2019_red["IDADE_INTROD_ESC"].replace(mapa_2019)
df_2021_red["IDADE_INTROD_ESC"] = df_2021_red["IDADE_INTROD_ESC"].replace(mapa_2021)
df_2023_red["IDADE_INTROD_ESC"] = df_2023_red["IDADE_INTROD_ESC"].replace(mapa_2023)

#set(df_2019_red["IDADE_INTROD_ESC"].unique()) - set(padrao_idade)
#set(df_2021_red["IDADE_INTROD_ESC"].unique()) - set(padrao_idade)
#set(df_2023_red["IDADE_INTROD_ESC"].unique()) - set(padrao_idade)

Questão 13 - A partir do primeiro ano do ensino fundamental, em que tipo de escola você estudou?

In [25]:
padrao_escola = [
    "Não respondeu",
    "Pública",
    "Particular",
    "Pública e particular"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Pública",
    "B": "Particular",
    "C": "Pública e particular"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Pública",
    "B": "Particular",
    "C": "Pública e particular"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Pública",
    "B": "Particular",
    "C": "Pública e particular"
}
df_2019_red["TIPO_ESCOLA"] = df_2019_red["TIPO_ESCOLA"].replace(mapa_2019)
df_2021_red["TIPO_ESCOLA"] = df_2021_red["TIPO_ESCOLA"].replace(mapa_2021)
df_2023_red["TIPO_ESCOLA"] = df_2023_red["TIPO_ESCOLA"].replace(mapa_2023)

#set(df_2019_red["TIPO_ESCOLA"].unique()) - set(padrao_escola)
#set(df_2021_red["TIPO_ESCOLA"].unique()) - set(padrao_escola)
#set(df_2023_red["TIPO_ESCOLA"].unique()) - set(padrao_escola)

Questão 16a - Fora da escola em dias de aula, quanto tempo você usa para: Lazer

Questão 16b	- Fora da escola em dias de aula, quanto tempo você usa para: Fazer cursos

Questão 16c - Fora da escola em dias de aula, quanto tempo você usa para: Fazer trabalhos domésticos	

Questão 16d	- Fora da escola em dias de aula, quanto tempo você usa para: Estudar

Questão 16e - Fora da escola em dias de aula, quanto tempo você usa para: Trabalhar fora de casa

In [26]:
padrao_tempo_atividades = [
    "Não respondeu",
    "Não usa o tempo para isso",
    "Menos de 1 hora",
    "Entre 1 e 2 horas",
    "Mais de 2 horas"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não usa o tempo para isso",
    "B": "Menos de 1 hora",
    "C": "Entre 1 e 2 horas",
    "D": "Mais de 2 horas"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não usa o tempo para isso",
    "B": "Menos de 1 hora",
    "C": "Entre 1 e 2 horas",
    "D": "Mais de 2 horas"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Não usa o tempo para isso",
    "B": "Menos de 1 hora",
    "C": "Entre 1 e 2 horas",
    "D": "Mais de 2 horas"
}
df_2019_red["TEMPO_LAZER"] = df_2019_red["TEMPO_LAZER"].replace(mapa_2019)
df_2021_red["TEMPO_LAZER"] = df_2021_red["TEMPO_LAZER"].replace(mapa_2021)
df_2023_red["TEMPO_LAZER"] = df_2023_red["TEMPO_LAZER"].replace(mapa_2023)

df_2019_red["TEMPO_CURSOS"] = df_2019_red["TEMPO_CURSOS"].replace(mapa_2019)
df_2021_red["TEMPO_CURSOS"] = df_2021_red["TEMPO_CURSOS"].replace(mapa_2021)
df_2023_red["TEMPO_CURSOS"] = df_2023_red["TEMPO_CURSOS"].replace(mapa_2023)

df_2019_red["TEMPO_TRAB_DOMES"] = df_2019_red["TEMPO_TRAB_DOMES"].replace(mapa_2019)
df_2021_red["TEMPO_TRAB_DOMES"] = df_2021_red["TEMPO_TRAB_DOMES"].replace(mapa_2021)
df_2023_red["TEMPO_TRAB_DOMES"] = df_2023_red["TEMPO_TRAB_DOMES"].replace(mapa_2023)

df_2019_red["TEMPO_ESTUDO"] = df_2019_red["TEMPO_ESTUDO"].replace(mapa_2019)
df_2021_red["TEMPO_ESTUDO"] = df_2021_red["TEMPO_ESTUDO"].replace(mapa_2021)
df_2023_red["TEMPO_ESTUDO"] = df_2023_red["TEMPO_ESTUDO"].replace(mapa_2023)

df_2019_red["TEMPO_TRABALHO"] = df_2019_red["TEMPO_TRABALHO"].replace(mapa_2019)
df_2021_red["TEMPO_TRABALHO"] = df_2021_red["TEMPO_TRABALHO"].replace(mapa_2021)
df_2023_red["TEMPO_TRABALHO"] = df_2023_red["TEMPO_TRABALHO"].replace(mapa_2023)

Questão 17 - Quando terminar o Ensino Fundamental você pretende

In [27]:
padrao_pos = [
    "Não respondeu",
    "Somente estudar",
    "Somente trabalhar",
    "Estudar e trabalhar",
    "Não sabe"
]
mapa_2019 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Somente estudar",
    "B": "Somente trabalhar",
    "C": "Estudar e trabalhar",
    "D": "Não sabe"
}
mapa_2021 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Somente estudar",
    "B": "Somente trabalhar",
    "C": "Estudar e trabalhar",
    "D": "Não sabe"
}
mapa_2023 = {
    "*": "Não respondeu",
    ".": "Não respondeu",
    "A": "Somente estudar",
    "B": "Somente trabalhar",
    "C": "Estudar e trabalhar",
    "D": "Não sabe"
}
df_2019_red["POS_EF"] = df_2019_red["POS_EF"].replace(mapa_2019)
df_2021_red["POS_EF"] = df_2021_red["POS_EF"].replace(mapa_2021)
df_2023_red["POS_EF"] = df_2023_red["POS_EF"].replace(mapa_2023)

#set(df_2019_red["POS_EF"].unique()) - set(padrao_pos)
#set(df_2021_red["POS_EF"].unique()) - set(padrao_pos)
#set(df_2023_red["POS_EF"].unique()) - set(padrao_pos)

#### 4. Unificação das bases dos diferentes anos
Realizar a união de bases de dados em uma análise multianual é fundamental para garantir uma visão mais completa, consistente e comparável ao longo do tempo. Isso permite unir as informações dos diferentes anos em uma única estrutura, facilitando sua exploração.

In [28]:
!pip install --upgrade numpy pandas pyarrow fastparquet

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: numpy in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (2.4.4)
Requirement already satisfied: pandas in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (3.0.3)
Requirement already satisfied: pyarrow in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (24.0.0)
Requirement already satisfied: fastparquet in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (2026.3.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from pandas) (2025.3)
Requirement already satisfied: cramjam>=2.3 in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (2026.3.0)
Requirement already satisfied: packaging in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (26.0)
Requirement already satisfied: six>=1.5 in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [30]:
gc.collect()

#!pip install fastparquet

df_unif = pd.concat([df_2019_red, df_2021_red, df_2023_red], ignore_index=True)

df_unif = df_unif.copy()

numericas = [
    "ANO",
    "REGIAO",
    "UF",
    "MUNICIPIO",
    "AREA",
    "ID_ESCOLA",
    "PUBLICA",
    "LOCALIZACAO",
    "ID_TURMA",
    "SERIE",
    "ID_ALUNO",
    "SITUACAO_CENSO",
    "PROFICIENCIA",
    "PESO",
    "PROFICIENCIA_MT",
    "ERRO_PADRAO_MT",
    "PROFICIENCIA_SAEB",
    "ERRO_PADRAO_MT_SAEB"      
]    
for col in numericas:
    df_unif[col] = pd.to_numeric(
    df_unif[col],
    errors="coerce"
)

categoricas = [
    "LINGUA_FALADA",
    "COR_RACA",
    "MORADOR_MAE",
    "MORADOR_PAI",
    "MORADOR_OUTROS",
    "ESCOL_MAE",
    "ESCOL_PAI",
    "FREQUENCIA_CONVERSA",
    "FREQUENCIA_INCENTIVO_ESTUDO",
    "FREQUENCIA_INCENTIVO_TAREFA",
    "FREQUENCIA_INCENTIVO_AULA",
    "FREQUENCIA_REUNIOES",
    "ASFALTO_CALCAMENTO",
    "AGUA_TRATADA",
    "ILUMINACAO",
    "QTD_GELADEIRA",
    "QTD_COMPUTADOR",
    "QTD_QUARTO",
    "QTD_TELEVISAO",
    "QTD_BANHEIRO",
    "QTD_CARRO",
    "TV_A_CABO",
    "WI-FI",
    "QUARTO",
    "MESA",
    "GARAGEM",
    "MICROONDAS",
    "ASPIRADOR",
    "MAQUINA",
    "FREEZER",
    "TEMPO_ATE_ESCOLA",
    "LOCOMOCAO_ATE_ESCOLA",
    "IDADE_INTROD_ESC",     
    "TIPO_ESCOLA",
    "REPROVACAO",
    "ABANDONO",
    "TEMPO_LAZER",
    "TEMPO_CURSOS",
    "TEMPO_TRAB_DOMES",
    "TEMPO_ESTUDO",
    "TEMPO_TRABALHO",
    "POS_EF"    
]
for col in categoricas:
    df_unif[col] = df_unif[col].astype("category")

processed_dir = r"C:\Users\emill\Downloads\TCC\processed"

os.makedirs(processed_dir, exist_ok=True)

out_path = os.path.join(processed_dir, "BASE_UNIF.parquet")

df_unif = pd.DataFrame(df_unif)
df_unif.reset_index(drop=True, inplace=True)

df_unif.to_parquet(out_path, index=False, engine="pyarrow")

#### 5. Remoção de duplicatas
Como cada linha do dataset representa exclusivamente um aluno, foi realizada uma verificação para identificar possíveis registros repetidos utilizando o comando abaixo. Esse procedimento garante que não haja inconsistências por múltiplas ocorrências de um mesmo aluno.

In [31]:
df_unif.duplicated().sum()

np.int64(0)

Como o resultado retornado foi 0, não existem registros repetidos no conjunto de dados, nenhuma linha precisou ser removida e sua estrutura permaneceu inalterada.

#### 6. Tratamento de erros e inconsistências de codificação
A qualidade de um conjunto de dados é fundamental para garantir a validade das análises. Por isso, as variáveis do conjunto de dados que contêm valores categóricos foram verificadas quanto a possíveis erros relacionados à codificação, como formatação inconsistente dos valores. 

##### Função UNIQUE
Validando se as possíveis respostas tem formatação diferente do esperado.

Ano de aplicação do Saeb

In [32]:
df_unif['ANO'].unique()

array([2019, 2021, 2023])

Código da Região

In [33]:
df_unif['REGIAO'].unique()

array([1, 2, 3, 4, 5])

1 - Norte

2 - Nordeste

3 - Sudeste	

4 - Sul	

5 - Centro-Oeste

Código da Unidade da Federação

In [34]:
df_unif['UF'].unique()

array([11, 12, 13, 14, 15, 16, 17, 21, 22, 23, 24, 25, 26, 27, 28, 29, 31,
       32, 33, 35, 41, 42, 43, 50, 51, 52, 53])

11-RO	           

12-AC	

13-AM	

14-RR	

15-PA	

16-AP	

17-TO	

21-MA	

22-PI	

23-CE	

24-RN	

25-PB	

26-PE	

27-AL	

28-SE	

29-BA	

31-MG	

32-ES	

33-RJ	

35-SP	

41-PR	

42-SC	

43-RS	

50-MS	

51-MT	

52-GO	

53-DF

Área

In [35]:
df_unif['AREA'].unique()

array([2, 1])

1 - Capital

2 - Interior

Indicador de escola pública

In [36]:
df_unif['PUBLICA'].unique()

array([1])

0 - Não pública

1 - Pública

Obs.: Aparece apenas o valor '1' devido à filtragem realizada na etapa 2.

Localização

In [37]:
df_unif['LOCALIZACAO'].unique()

array([1, 2])

1 - Urbana

2 - Rural

Série

In [38]:
df_unif['SERIE'].unique()

array([9])

9 - 9º ano do Ensino Fundamental

Indicador de Consistência com o Censo Escolar 20192

In [39]:
df_unif['SITUACAO_CENSO'].unique()

array([1, 0])

0 - Não consistente

1 - Consistente

Indicador para cálculo da proficiência (no mínimo três itens respondidos no caderno de provas de Língua Portuguesa e Matemática)

In [40]:
df_unif['PROFICIENCIA'].unique()

array([1])

0 - Não

1 - Sim	

Obs.: Aparece apenas o valor '1' devido à filtragem realizada na etapa 2.

A verificação das variáveis demonstrou que não há inconsistências de codificação, todas os valores das colunas analisadas estão de acordo com o esperado. Isso garante maior confiabilidade aos dados e elimina a necessidade de tratamentos adicionais nessas variáveis.

#### 7. Valores nulos

As informações gerais sobre o conjunto de dados foram exibidas novamente para determinar as colunas que continham valores nulos (ou seja, aquelas cuja contagem de valores não nulos não é igual ao número de observações).

In [41]:
df_unif.info(verbose=True, show_counts=True)

<class 'pandas.DataFrame'>
RangeIndex: 5850766 entries, 0 to 5850765
Data columns (total 60 columns):
 #   Column                       Non-Null Count    Dtype
---  ------                       --------------    -----
 0   ANO                          5850766 non-null  int64
 1   REGIAO                       5850766 non-null  int64
 2   UF                           5850766 non-null  int64
 3   MUNICIPIO                    5850766 non-null  int64
 4   AREA                         5850766 non-null  int64
 5   ID_ESCOLA                    5850766 non-null  int64
 6   PUBLICA                      5850766 non-null  int64
 7   LOCALIZACAO                  5850766 non-null  int64
 8   ID_TURMA                     5850766 non-null  int64
 9   SERIE                        5850766 non-null  int64
 10  ID_ALUNO                     5850766 non-null  int64
 11  SITUACAO_CENSO               5850766 non-null  int64
 12  PROFICIENCIA                 5850766 non-null  int64
 13  PESO                         5826884 non-null  float64
 14  PROFICIENCIA_MT              5850766 non-null  float64
 15  ERRO_PADRAO_MT               5850766 non-null  float64
 16  PROFICIENCIA_SAEB            5850766 non-null  float64
 17  ERRO_PADRAO_MT_SAEB          5850766 non-null  float64
 18  LINGUA_FALADA                5850766 non-null  category
 19  COR_RACA                     5850766 non-null  category
 20  MORADOR_MAE                  5850766 non-null  category
 21  MORADOR_PAI                  5850766 non-null  category
 22  MORADOR_OUTROS               5850766 non-null  category
 23  ESCOL_MAE                    5850766 non-null  category
 24  ESCOL_PAI                    5850766 non-null  category
 25  FREQUENCIA_CONVERSA          5850766 non-null  category
 26  FREQUENCIA_INCENTIVO_ESTUDO  5850766 non-null  category
 27  FREQUENCIA_INCENTIVO_TAREFA  5850766 non-null  category
 28  FREQUENCIA_INCENTIVO_AULA    5850766 non-null  category
 29  FREQUENCIA_REUNIOES          5850766 non-null  category
 30  ASFALTO_CALCAMENTO           5850766 non-null  category
 31  AGUA_TRATADA                 5850766 non-null  category
 32  ILUMINACAO                   5850766 non-null  category
 33  QTD_GELADEIRA                5850766 non-null  category
 34  QTD_COMPUTADOR               5850766 non-null  category
 35  QTD_QUARTO                   5850766 non-null  category
 36  QTD_TELEVISAO                5850766 non-null  category
 37  QTD_BANHEIRO                 5850766 non-null  category
 38  QTD_CARRO                    5850766 non-null  category
 39  TV_A_CABO                    5850766 non-null  category
 40  WI-FI                        5850766 non-null  category
 41  QUARTO                       5850766 non-null  category
 42  MESA                         5850766 non-null  category
 43  GARAGEM                      5850766 non-null  category
 44  MICROONDAS                   5850766 non-null  category
 45  ASPIRADOR                    5850766 non-null  category
 46  MAQUINA                      5850766 non-null  category
 47  FREEZER                      5850766 non-null  category
 48  TEMPO_ATE_ESCOLA             5850766 non-null  category
 49  LOCOMOCAO_ATE_ESCOLA         5850766 non-null  category
 50  IDADE_INTROD_ESC             5850766 non-null  category
 51  TIPO_ESCOLA                  5850766 non-null  category
 52  REPROVACAO                   5850766 non-null  category
 53  ABANDONO                     5850766 non-null  category
 54  TEMPO_LAZER                  5850766 non-null  category
 55  TEMPO_CURSOS                 5850766 non-null  category
 56  TEMPO_TRAB_DOMES             5850766 non-null  category
 57  TEMPO_ESTUDO                 5850766 non-null  category
 58  TEMPO_TRABALHO               5850766 non-null  category
 59  POS_EF                       5850766 non-null  category
dtypes: category(42), float64(5), int64(13)
memory usage: 1.0 GB

In [ ]:
#df_unif.query('PESO != PESO')

#### 8. Reinicialização do índice

Como algumas linhas foram descartadas nas etapas anteriores do processo de limpeza de dados, os índices das entradas foram redefinidos (por meio da função reset_index) para refletir o número atualizado de observações.

In [42]:
df_unif = df_unif.reset_index(drop=True)
df_unif

,ANO,REGIAO,UF,MUNICIPIO,AREA,ID_ESCOLA,PUBLICA,LOCALIZACAO,ID_TURMA,SERIE,...,IDADE_INTROD_ESC,TIPO_ESCOLA,REPROVACAO,ABANDONO,TEMPO_LAZER,TEMPO_CURSOS,TEMPO_TRAB_DOMES,TEMPO_ESTUDO,TEMPO_TRABALHO,POS_EF
0,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,Entre 4 e 7,Pública,Sim,Não,Mais de 2 horas,Não usa o tempo para isso,Mais de 2 horas,Menos de 1 hora,Não usa o tempo para isso,Estudar e trabalhar
1,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,Entre 4 e 7,Pública,Não,Não,Mais de 2 horas,Não usa o tempo para isso,Mais de 2 horas,Menos de 1 hora,Não usa o tempo para isso,Estudar e trabalhar
2,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,Entre 4 e 7,Pública,Não,Não,Mais de 2 horas,Não usa o tempo para isso,Mais de 2 horas,Entre 1 e 2 horas,Não usa o tempo para isso,Não sabe
3,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,Entre 4 e 7,Pública,Não,Não,Entre 1 e 2 horas,Não usa o tempo para isso,Mais de 2 horas,Entre 1 e 2 horas,Não usa o tempo para isso,Não sabe
4,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,Entre 4 e 7,Pública,Não,Não,Entre 1 e 2 horas,Não usa o tempo para isso,Não respondeu,Menos de 1 hora,Não usa o tempo para isso,Estudar e trabalhar
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850761,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,Entre 4 e 7,Pública e particular,Não,Não,Mais de 2 horas,Menos de 1 hora,Menos de 1 hora,Entre 1 e 2 horas,Não usa o tempo para isso,Estudar e trabalhar
5850762,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,Entre 4 e 7,Pública,Não,Não,Mais de 2 horas,Não usa o tempo para isso,Menos de 1 hora,Menos de 1 hora,Não usa o tempo para isso,Não sabe
5850763,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,Entre 4 e 7,Pública,Não,Não,Mais de 2 horas,Entre 1 e 2 horas,Não usa o tempo para isso,Menos de 1 hora,Não usa o tempo para isso,Estudar e trabalhar
5850764,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,3 ou menos,Pública e particular,Não,Não,Mais de 2 horas,Mais de 2 horas,Mais de 2 horas,Entre 1 e 2 horas,Entre 1 e 2 horas,Estudar e trabalhar
5850765,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,Não respondeu,Não respondeu,Não,Não,Mais de 2 horas,Não usa o tempo para isso,Menos de 1 hora,Menos de 1 hora,Não usa o tempo para isso,Estudar e trabalhar

Em resumo, o conjunto de dados limpo possui 5.850.766 observações (linhas), representando uma redução de 21,82% em relação às 7.483.775 observações originais. Foi necessário descartar mais de um quinto das observações para manter a integridade dos dados para análise, e adequar aos objetivos do estudo. As observações retiradas constam na Etapa 2, onde foi aplicado um filtro para identificar e selecionar apenas os registros de interesse, aqueles de alunos de escolas públicas que efetivamente tiveram seu desempenho avaliado na avaliação do SAEB em cada ano.

In [ ]:
#dados = {
#    "Número de observações retiradas": ["", "", ""],
#    "Percentagem em relação ao número original de entradas": [0,0,0],
#    "Motivo da retirada": ["", "", ""]
#}
#
#df = pd.DataFrame(dados)
#df.style.hide(axis="index")