In [4]:
import os
import pandas as pd
import numpy as np
import sys
import gc

!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: openpyxl in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from openpyxl) (2.0.0)

In [7]:
gc.collect
df_saeb_2019 = pd.read_csv("2019/TS_ALUNO_9EF.csv",  encoding='latin-1', sep=";", dtype='str')

In [8]:
gc.collect()
df_saeb_2021 = pd.read_csv("2021/TS_ALUNO_9EF.csv", encoding='latin-1', sep=";", dtype='str')

In [9]:
gc.collect()
df_saeb_2023 = pd.read_csv("2023/TS_ALUNO_9EF.csv",  encoding='latin-1', sep=";", dtype='str')

### Pré-processamento dos dados
Esta seção descreve o pré-processamento realizado nos dados antes de submetê-los à análise. São descritos as motivações e os processos relacionados à fusão de conjuntos e à limpeza de dados. 

#### 1. Filtro das colunas
Os datasets dos diferentes anos possuem variáveis diferentes entre si, portanto, algumas colunas devem ser desconsideradas por estarem presentes apenas na base de algum dos anos, o que comprometeria a consistência das análises multianuais.

##### 2019
Em 2019, serão removidas as seguintes variáveis (colunas): ID_BLOCO_3_CH, TX_RESP_BLOCO3_CH, TX_RESP_Q003c, TX_RESP_Q003d, TX_RESP_Q007, TX_RESP_Q009b, TX_RESP_Q018a, TX_RESP_Q018b, TX_RESP_Q018c, pois elas não estão presentes em todas as bases.

In [10]:
df_2019_red = df_saeb_2019.drop(columns=[
     'ID_BLOCO_3_CH', 'TX_RESP_BLOCO3_CH', 'TX_RESP_Q003C', 'TX_RESP_Q003D', 'TX_RESP_Q007', 'TX_RESP_Q009B', 'TX_RESP_Q018A', 
     'TX_RESP_Q018B', 'TX_RESP_Q018C'
])
df_2019_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q013,TX_RESP_Q014,TX_RESP_Q015,TX_RESP_Q016,TX_RESP_Q017A,TX_RESP_Q017B,TX_RESP_Q017C,TX_RESP_Q017D,TX_RESP_Q017E,TX_RESP_Q019
0,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,B,A,D,A,D,B,A,C
1,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,B,A,C
2,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,C,A,D
3,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,D,C,A,D
4,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,*,B,A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2388926,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,.,.,.,.,.,.,.,.,.,.
2388927,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,C,A,A,D,B,C,D,A,A
2388928,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,A,B,A,D,A,A,C,A,C
2388929,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,C,A,B,A,D,A,B,B,A,B
2388930,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,.,.,.,.,.,.,.,.,.,.

##### 2021
Em 2021, serão removidas as seguintes variáveis (colunas): ID_BLOCO_3_CH, TX_RESP_BLOCO3_CH, IN_INSE, INSE_ALUNO, NU_TIPO_NIVEL_INSE, PESO_ALUNO_INSE, TX_RESP_Q01, TX_RESP_Q02, TX_RESP_Q05, TX_RESP_Q06c, TX_RESP_Q06d, TX_RESP_Q09a, TX_RESP_Q11b, TX_RESP_Q11h, TX_RESP_Q15, TX_RESP_Q22a, TX_RESP_Q22b, TX_RESP_Q22c, TX_RESP_Q22d, TX_RESP_Q22e, TX_RESP_Q22f, TX_RESP_Q22g, TX_RESP_Q22h, TX_RESP_Q22i, pois elas não estão presentes em todas as bases.

In [12]:
df_2021_red = df_saeb_2021.drop(columns=[
    'ID_BLOCO_3_CH', 'TX_RESP_BLOCO3_CH', 'IN_INSE', 'INSE_ALUNO', 'NU_TIPO_NIVEL_INSE', 'PESO_ALUNO_INSE', 'TX_RESP_Q01', 'TX_RESP_Q02', 'TX_RESP_Q05',
    'TX_RESP_Q06c', 'TX_RESP_Q06d', 'TX_RESP_Q09a', 'TX_RESP_Q11b', 'TX_RESP_Q11h', 'TX_RESP_Q15', 'TX_RESP_Q22a', 'TX_RESP_Q22b', 'TX_RESP_Q22c', 
    'TX_RESP_Q22d', 'TX_RESP_Q22e', 'TX_RESP_Q22f', 'TX_RESP_Q22g', 'TX_RESP_Q22h', 'TX_RESP_Q22i'
])
df_2021_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q16,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20a,TX_RESP_Q20b,TX_RESP_Q20c,TX_RESP_Q20d,TX_RESP_Q20e,TX_RESP_Q21
0,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,A,A,A,A,C,B,D,D,B,C
1,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,B,C,C,A,B,D,D,D,C,B
2,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,.,.,.,.,.,.,.,.,.,.
3,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,.,.,.,.,.,.,.,.,.,.
4,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,A,.,A,B,*,A,A,D,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591932,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591933,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591934,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591935,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.
2591936,2021,5,53,6322169,1,61397110,0,1,1475064,9,...,.,.,.,.,.,.,.,.,.,.

##### 2023
Em 2023, serão removidas as seguintes variáveis (colunas): IN_INSE, INSE_ALUNO, NU_TIPO_NIVEL_INSE, PESO_ALUNO_INSE, TX_RESP_Q01, TX_RESP_Q02, TX_RESP_Q05a, TX_RESP_Q05b, TX_RESP_Q05c, TX_RESP_Q06, TX_RESP_Q07c, TX_RESP_Q07d, TX_RESP_Q10a, TX_RESP_Q12g, TX_RESP_Q15a, TX_RESP_Q15b, TX_RESP_Q22a, TX_RESP_Q22b, TX_RESP_Q22c, TX_RESP_Q22d, TX_RESP_Q22e, TX_RESP_Q22f, TX_RESP_Q22g, TX_RESP_Q22h, TX_RESP_Q23a, TX_RESP_Q23b, TX_RESP_Q23c, TX_RESP_Q23d, TX_RESP_Q23e, TX_RESP_Q23f, TX_RESP_Q23g, TX_RESP_Q23h, TX_RESP_Q23i, pois elas não estão presentes em todas as bases.

In [14]:
df_2023_red = df_saeb_2023.drop(columns=[
    'IN_INSE', 'INSE_ALUNO', 'NU_TIPO_NIVEL_INSE', 'PESO_ALUNO_INSE', 'TX_RESP_Q01', 'TX_RESP_Q02', 'TX_RESP_Q05a', 'TX_RESP_Q05b', 'TX_RESP_Q05c', 
    'TX_RESP_Q06', 'TX_RESP_Q07c', 'TX_RESP_Q07d', 'TX_RESP_Q10a', 'TX_RESP_Q12g', 'TX_RESP_Q15a', 'TX_RESP_Q15b', 'TX_RESP_Q22a', 'TX_RESP_Q22b', 
    'TX_RESP_Q22c', 'TX_RESP_Q22d', 'TX_RESP_Q22e', 'TX_RESP_Q22f', 'TX_RESP_Q22g', 'TX_RESP_Q22h', 'TX_RESP_Q23a', 'TX_RESP_Q23b', 'TX_RESP_Q23c', 
    'TX_RESP_Q23d', 'TX_RESP_Q23e', 'TX_RESP_Q23f', 'TX_RESP_Q23g', 'TX_RESP_Q23h', 'TX_RESP_Q23i'
])
df_2023_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20,TX_RESP_Q21a,TX_RESP_Q21b,TX_RESP_Q21c,TX_RESP_Q21d,TX_RESP_Q21e,TX_RESP_Q24
0,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,A,A,D,D,D,B
1,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,.,.,.,.,.,.,.,.,.,.
2,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,.,.,.,.,.,.,.,.,.,.
3,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,.,.,.,.,D,A
4,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,.,.,.,.,.,.,.,.,.,.
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502902,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,A,A,A,B,C,A,A,D,C
2502903,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,A,C,A,A,C,D,D,C,D,C
2502904,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,.,.,.,.,.,.,.,.
2502905,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,A,A,B,A,B,A,D,C
2502906,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,.,.,.,.,.,.,.,.

#### 2. Removendo os dados dos alunos que não são objetos do estudo
Como o objetivo do estudo é analisar o desempenho em matemática dos alunos de escolas públicas, serão selecionados apenas os dados desses alunos (a variável IN_PUBLICA é responsável por carregar essa informação). Dentro desse conjunto, é necessário avaliar a participação de cada aluno, e se ele cumpriu o requisito mínimo necessário para ter seu desempenho avaliado (a variável IN_PROFICIENCIA_MT, que é o indicador para cálculo da proficiência em Matemática - no mínimo três itens respondidos no caderno de provas de Língua Portuguesa e Matemática - engloba essas informações). 
Registros além desses não contribuem para as análises propostas, portanto, será aplicado um filtro para identificar e selecionar apenas os registros de interesse, garantindo que o dataset final contenha apenas participantes de escolas públicas que efetivamente tiveram seu desempenho avaliado.

##### 2019

In [11]:
df_2019_red = df_2019_red[(df_2019_red['IN_PROFICIENCIA_MT'] == '1') & (df_2019_red['IN_PUBLICA'] == '1')].copy()
#df_2019_red['PROFICIENCIA_MT_SAEB'] = df_2019_red['PROFICIENCIA_MT_SAEB'].astype(float)
#df_2019_red = df_2019_red.drop('IN_PUBLICA', axis=1)
#df_2019_red = df_2019_red.drop('IN_PROFICIENCIA_MT', axis=1)
df_2019_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q013,TX_RESP_Q014,TX_RESP_Q015,TX_RESP_Q016,TX_RESP_Q017A,TX_RESP_Q017B,TX_RESP_Q017C,TX_RESP_Q017D,TX_RESP_Q017E,TX_RESP_Q019
0,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,B,A,D,A,D,B,A,C
1,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,B,A,C
2,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,B,A,A,A,D,A,D,C,A,D
3,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,D,C,A,D
4,2019,1,11,6311030,2,61255632,1,1,1030927,9,...,C,A,A,A,C,A,*,B,A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2388923,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,B,A,B,A,D,B,*,B,A,C
2388924,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,A,C,A,D,A,B,B,B,A
2388927,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,C,A,A,D,B,C,D,A,A
2388928,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,A,A,B,A,D,A,A,C,A,C
2388929,2019,5,53,6316599,1,61322272,1,1,1067040,9,...,C,A,B,A,D,A,B,B,A,B

##### 2021

In [13]:
df_2021_red = df_2021_red[(df_2021_red['IN_PROFICIENCIA_MT'] == '1') & (df_2021_red['IN_PUBLICA'] == '1')].copy()
df_2021_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q16,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20a,TX_RESP_Q20b,TX_RESP_Q20c,TX_RESP_Q20d,TX_RESP_Q20e,TX_RESP_Q21
0,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,A,A,A,A,C,B,D,D,B,C
1,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,B,C,C,A,B,D,D,D,C,B
4,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,A,.,A,B,*,A,A,D,C
5,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,B,A,B,A,C,*,B,B,B,C
6,2021,1,11,6316600,2,61324549,1,1,1324152,9,...,C,A,A,A,B,B,C,D,D,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591699,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,B,A,A,A,C,A,C,D,C,C
2591701,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,B,A,A,A,.,.,.,.,.,C
2591702,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,C,A,A,A,C,B,B,A,D,C
2591704,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,C,A,A,A,B,D,B,A,D,D
2591705,2021,5,53,6322169,1,61397023,1,1,1435004,9,...,B,A,A,A,C,A,B,D,C,C

##### 2023

In [15]:
df_2023_red = df_2023_red[(df_2023_red['IN_PROFICIENCIA_MT'] == '1') & (df_2023_red['IN_PUBLICA'] == '1')].copy()
df_2023_red

,ID_SAEB,ID_REGIAO,ID_UF,ID_MUNICIPIO,ID_AREA,ID_ESCOLA,IN_PUBLICA,ID_LOCALIZACAO,ID_TURMA,ID_SERIE,...,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20,TX_RESP_Q21a,TX_RESP_Q21b,TX_RESP_Q21c,TX_RESP_Q21d,TX_RESP_Q21e,TX_RESP_Q24
0,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,A,A,D,D,D,B
3,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,C,A,A,A,.,.,.,.,D,A
7,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,B,A,B,A,B,A,D,A,C,A
9,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,B,A,B,A,B,A,C,D,B,C
11,2023,1,11,6322170,2,61400934,1,1,1704202,9,...,B,A,A,A,B,A,D,A,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502898,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,C,A,A,C,B,B,A,D,C
2502900,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,A,A,A,B,A,B,A,D,D
2502902,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,C,A,A,A,B,C,A,A,D,C
2502903,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,A,C,A,A,C,D,D,C,D,C
2502905,2023,5,53,6327738,1,61470349,1,1,1719813,9,...,.,.,A,A,B,A,B,A,D,C

#### 3. Unificação das bases dos diferentes anos
Realizar a união de bases de dados em uma análise multianual é fundamental para garantir uma visão mais completa, consistente e comparável ao longo do tempo. Isso permite unir as informações dos diferentes anos em uma única estrutura, facilitando sua exploração.

In [16]:
gc.collect()

!pip install fastparquet

df_unif = pd.concat([df_2019_red, df_2021_red, df_2023_red], ignore_index=True)
processed_dir = r"C:\Users\emill\Downloads\TCC\processed"
os.makedirs(processed_dir, exist_ok=True)

out_path = os.path.join(processed_dir, "BASE_UNIF.parquet")

df_unif.to_parquet(out_path, index=False, engine="fastparquet", compression="gzip")

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: fastparquet in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (2026.3.0)
Requirement already satisfied: pandas>=1.5.0 in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (3.0.1)
Requirement already satisfied: numpy in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (2.4.3)
Requirement already satisfied: cramjam>=2.3 in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (2026.3.0)
Requirement already satisfied: packaging in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from fastparquet) (26.0)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from pandas>=1.5.0->fastparquet) (2025.3)
Requirement already satisfied: six>=1.5 in C:\Users\emill\AppData\Roaming\Python\Python313\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.17.0)