Importando as bibliotecas e módulos necessários:

In [2]:
import os
import pandas as pd
import numpy as np
import sys
import gc

!pip install openpyxl

Requirement already satisfied: openpyxl in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

In [4]:
gc.collect
df_saeb_2019 = pd.read_csv("2019/TS_ALUNO_9EF.csv",  encoding='latin-1', sep=";", dtype='category')

In [5]:
gc.collect()
df_saeb_2021 = pd.read_csv("2021/TS_ALUNO_9EF.csv", encoding='latin-1', sep=";", dtype='category')

In [6]:
gc.collect()
df_saeb_2023 = pd.read_csv("2023/TS_ALUNO_9EF.csv",  encoding='latin-1', sep=";", dtype='category')

### 1. Pré-processamento dos dados
Esta seção descreve o pré-processamento realizado nos dados antes de submetê-los à análise. 

#### 1.1 Filtro das colunas
Embora o dataset original disponibilizado contenha um conjunto extenso de informações, optou-se por manter apenas as variáveis relevantes aos objetivos do estudo.

In [7]:
colunas_2019 = ['ID_SAEB','IN_PUBLICA','IN_PROFICIENCIA_MT','PROFICIENCIA_MT_SAEB','TX_RESP_Q002','TX_RESP_Q003A','TX_RESP_Q003B',
                'TX_RESP_Q003C','TX_RESP_Q003D','TX_RESP_Q003E','TX_RESP_Q004','TX_RESP_Q005','TX_RESP_Q006A','TX_RESP_Q006B','TX_RESP_Q006C',
                'TX_RESP_Q006D','TX_RESP_Q006E','TX_RESP_Q008A','TX_RESP_Q008B','TX_RESP_Q008C','TX_RESP_Q009A','TX_RESP_Q009B','TX_RESP_Q009C',
                'TX_RESP_Q009D','TX_RESP_Q009E','TX_RESP_Q009F','TX_RESP_Q009G','TX_RESP_Q010A','TX_RESP_Q010B', 'TX_RESP_Q010C','TX_RESP_Q010D',
                'TX_RESP_Q010E','TX_RESP_Q010F','TX_RESP_Q010G','TX_RESP_Q010H','TX_RESP_Q010I', 'TX_RESP_Q011','TX_RESP_Q012','TX_RESP_Q013',
                'TX_RESP_Q014','TX_RESP_Q015','TX_RESP_Q016','TX_RESP_Q017A','TX_RESP_Q017B','TX_RESP_Q017C','TX_RESP_Q017D','TX_RESP_Q017E',
                'TX_RESP_Q019']
saeb_mt_2019 = df_saeb_2019.filter(items=colunas_2019)
saeb_mt_2019 = saeb_mt_2019[(saeb_mt_2019['IN_PROFICIENCIA_MT'] == '1') & (saeb_mt_2019['IN_PUBLICA'] == '1')].copy()
saeb_mt_2019['PROFICIENCIA_MT_SAEB'] = saeb_mt_2019['PROFICIENCIA_MT_SAEB'].astype(float)
saeb_mt_2019 = saeb_mt_2019.drop('IN_PUBLICA', axis=1)
saeb_mt_2019 = saeb_mt_2019.drop('IN_PROFICIENCIA_MT', axis=1)
saeb_mt_2019

,ID_SAEB,PROFICIENCIA_MT_SAEB,TX_RESP_Q002,TX_RESP_Q003A,TX_RESP_Q003B,TX_RESP_Q003C,TX_RESP_Q003D,TX_RESP_Q003E,TX_RESP_Q004,TX_RESP_Q005,...,TX_RESP_Q013,TX_RESP_Q014,TX_RESP_Q015,TX_RESP_Q016,TX_RESP_Q017A,TX_RESP_Q017B,TX_RESP_Q017C,TX_RESP_Q017D,TX_RESP_Q017E,TX_RESP_Q019
0,2019,239.920418,A,B,B,B,A,A,A,A,...,C,A,B,A,D,A,D,B,A,C
1,2019,244.042645,C,B,A,B,B,B,E,D,...,B,A,A,A,D,A,D,B,A,C
2,2019,230.205828,C,B,.,.,.,.,F,F,...,B,A,A,A,D,A,D,C,A,D
3,2019,268.977498,C,B,B,B,A,A,E,D,...,C,A,A,A,C,A,D,C,A,D
4,2019,260.803189,A,B,B,B,A,A,B,A,...,C,A,A,A,C,A,*,B,A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2388923,2019,300.629099,A,B,B,B,A,A,C,D,...,B,A,B,A,D,B,*,B,A,C
2388924,2019,251.334973,C,B,B,A,A,A,C,C,...,A,A,C,A,D,A,B,B,B,A
2388927,2019,314.472176,A,B,B,.,.,.,E,E,...,A,C,A,A,D,B,C,D,A,A
2388928,2019,288.022305,B,B,B,B,A,A,B,A,...,A,A,B,A,D,A,A,C,A,C
2388929,2019,227.039360,B,B,B,A,A,A,D,D,...,C,A,B,A,D,A,B,B,A,B

In [8]:
colunas_2021 = ['ID_SAEB','IN_PUBLICA','IN_PROFICIENCIA_MT','PROFICIENCIA_MT_SAEB','TX_RESP_Q01','TX_RESP_Q02','TX_RESP_Q04',
                'TX_RESP_Q05','TX_RESP_Q06A','TX_RESP_Q06B','TX_RESP_Q06C','TX_RESP_Q06D','TX_RESP_Q06E','TX_RESP_Q07','TX_RESP_Q08','TX_RESP_Q09A',
                'TX_RESP_Q09B','TX_RESP_Q09C','TX_RESP_Q09D','TX_RESP_Q09E','TX_RESP_Q09F','TX_RESP_Q10A','TX_RESP_Q10B','TX_RESP_Q10C',
                'TX_RESP_Q11A','TX_RESP_Q11B','TX_RESP_Q11C','TX_RESP_Q11D','TX_RESP_Q11E','TX_RESP_Q11F','TX_RESP_Q11G','TX_RESP_Q11H', 
                'TX_RESP_Q12A','TX_RESP_Q12B', 'TX_RESP_Q12C','TX_RESP_Q12D','TX_RESP_Q12E','TX_RESP_Q12F','TX_RESP_Q12G','TX_RESP_Q12H',
                'TX_RESP_Q12I','TX_RESP_Q13','TX_RESP_Q14','TX_RESP_Q15','TX_RESP_Q16','TX_RESP_Q17','TX_RESP_Q18','TX_RESP_Q19','TX_RESP_Q20A',
                'TX_RESP_Q20B','TX_RESP_Q20C','TX_RESP_Q20D','TX_RESP_Q20E','TX_RESP_Q21','TX_RESP_Q22A','TX_RESP_Q22B','TX_RESP_Q22C','TX_RESP_Q22D',
                'TX_RESP_Q22E','TX_RESP_Q22F','TX_RESP_Q22G','TX_RESP_Q22H','TX_RESP_Q22I']
saeb_mt_2021 = df_saeb_2021.filter(items=colunas_2021)
saeb_mt_2021 = saeb_mt_2021[(saeb_mt_2021['IN_PROFICIENCIA_MT'] == '1') & (saeb_mt_2021['IN_PUBLICA'] == '1')].copy()
saeb_mt_2021['PROFICIENCIA_MT_SAEB'] = saeb_mt_2021['PROFICIENCIA_MT_SAEB'].astype(float)
saeb_mt_2021 = saeb_mt_2021.drop('IN_PUBLICA', axis=1)
saeb_mt_2021 = saeb_mt_2021.drop('IN_PROFICIENCIA_MT', axis=1)
saeb_mt_2021

,ID_SAEB,PROFICIENCIA_MT_SAEB,TX_RESP_Q01,TX_RESP_Q02,TX_RESP_Q04,TX_RESP_Q05,TX_RESP_Q07,TX_RESP_Q08,TX_RESP_Q13,TX_RESP_Q14,TX_RESP_Q15,TX_RESP_Q16,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q21
0,2021,234.739479,A,B,A,B,D,F,C,D,B,A,A,A,A,C
1,2021,165.188854,A,E,C,B,F,F,B,D,B,B,C,C,A,B
4,2021,208.589694,B,B,A,B,B,B,C,A,A,C,A,.,A,C
5,2021,188.686380,B,E,C,B,F,F,C,D,B,B,A,B,A,C
6,2021,283.393079,B,C,D,B,F,F,A,A,A,C,A,A,A,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2591699,2021,161.642430,A,C,C,B,C,B,A,A,A,B,A,A,A,C
2591701,2021,207.928823,A,C,C,B,D,E,C,D,B,B,A,A,A,C
2591702,2021,309.389104,B,C,C,B,D,D,C,D,A,C,A,A,A,C
2591704,2021,263.621671,A,B,A,B,D,C,.,.,A,C,A,A,A,D
2591705,2021,294.178175,B,C,A,B,F,F,A,C,B,B,A,A,A,C

In [9]:
colunas_2023 = ['ID_SAEB','IN_PUBLICA','IN_PROFICIENCIA_MT','PROFICIENCIA_MT_SAEB','TX_RESP_Q01','TX_RESP_Q02','TX_RESP_Q04',
                'TX_RESP_Q06','TX_RESP_Q07a','TX_RESP_Q07b','TX_RESP_Q07c','TX_RESP_Q07d','TX_RESP_Q07e','TX_RESP_Q08','TX_RESP_Q09','TX_RESP_Q10a',
                'TX_RESP_Q10b','TX_RESP_Q10c','TX_RESP_Q10d','TX_RESP_Q10e','TX_RESP_Q10f','TX_RESP_Q11a','TX_RESP_Q11b','TX_RESP_Q11c', 
                'TX_RESP_Q12a','TX_RESP_Q12b', 'TX_RESP_Q12c','TX_RESP_Q12d','TX_RESP_Q12e','TX_RESP_Q12f','TX_RESP_Q12g','TX_RESP_Q13a','TX_RESP_Q13b',
                'TX_RESP_Q13c','TX_RESP_Q13d','TX_RESP_Q13e','TX_RESP_Q13f','TX_RESP_Q13g','TX_RESP_Q13h','TX_RESP_Q13i','TX_RESP_Q14','TX_RESP_Q15a',
                'TX_RESP_Q15b','TX_RESP_Q16','TX_RESP_Q17','TX_RESP_Q18','TX_RESP_Q19','TX_RESP_Q20','TX_RESP_Q21a','TX_RESP_Q21b','TX_RESP_Q21c','TX_RESP_Q21d',
                'TX_RESP_Q21e','TX_RESP_Q24']
saeb_mt_2023 = df_saeb_2023.filter(items=colunas_2023)
saeb_mt_2023 = saeb_mt_2023[(saeb_mt_2023['IN_PROFICIENCIA_MT'] == '1') & (saeb_mt_2023['IN_PUBLICA'] == '1')].copy()
saeb_mt_2023['PROFICIENCIA_MT_SAEB'] = saeb_mt_2023['PROFICIENCIA_MT_SAEB'].astype(float)
saeb_mt_2023 = saeb_mt_2023.drop('IN_PUBLICA', axis=1)
saeb_mt_2023 = saeb_mt_2023.drop('IN_PROFICIENCIA_MT', axis=1)
saeb_mt_2023

,ID_SAEB,PROFICIENCIA_MT_SAEB,TX_RESP_Q01,TX_RESP_Q02,TX_RESP_Q04,TX_RESP_Q06,TX_RESP_Q07a,TX_RESP_Q07b,TX_RESP_Q07c,TX_RESP_Q07d,...,TX_RESP_Q17,TX_RESP_Q18,TX_RESP_Q19,TX_RESP_Q20,TX_RESP_Q21a,TX_RESP_Q21b,TX_RESP_Q21c,TX_RESP_Q21d,TX_RESP_Q21e,TX_RESP_Q24
0,2023,218.734766,A,B,C,D,B,B,A,A,...,C,A,A,A,A,A,D,D,D,B
3,2023,186.094318,B,D,B,C,B,.,.,.,...,C,A,A,A,.,.,.,.,D,A
7,2023,242.608224,B,C,C,C,B,B,.,.,...,B,A,B,A,B,A,D,A,C,A
9,2023,227.650431,A,B,.,C,B,B,A,A,...,B,A,B,A,B,A,C,D,B,C
11,2023,266.778246,B,B,C,C,A,A,.,.,...,B,A,A,A,B,A,D,A,C,C
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2502898,2023,241.227963,A,B,C,D,B,B,.,.,...,C,C,A,A,C,B,B,A,D,C
2502900,2023,220.519967,A,C,A,D,A,A,A,B,...,C,A,A,A,B,A,B,A,D,D
2502902,2023,341.751041,A,C,A,D,B,B,.,A,...,C,A,A,A,B,C,A,A,D,C
2502903,2023,328.555589,A,C,C,D,B,B,A,A,...,A,C,A,A,C,D,D,C,D,C
2502905,2023,220.753374,B,B,B,B,B,B,.,.,...,.,.,A,A,B,A,B,A,D,C

In [12]:
gc.collect()
data_dir = r"C:\Users\Admin\TCC\data"
os.makedirs(data_dir, exist_ok=True)
out_path = os.path.join(data_dir, "2019.parquet")
saeb_mt_2019.to_parquet(out_path, index=False, engine="fastparquet", compression="gzip")
out_path = os.path.join(data_dir, "2021.parquet")
saeb_mt_2021.to_parquet(out_path, index=False, engine="fastparquet", compression="gzip")
out_path = os.path.join(data_dir, "2023.parquet")
saeb_mt_2019.to_parquet(out_path, index=False, engine="fastparquet", compression="gzip")

#### 1.2 Unificação das bases dos diferentes anos

In [10]:
gc.collect()

!pip install fastparquet

df_unif = pd.concat([saeb_mt_2019, saeb_mt_2021, saeb_mt_2023], ignore_index=True)
processed_dir = r"C:\Users\Admin\TCC\processed"
os.makedirs(processed_dir, exist_ok=True)

out_path = os.path.join(processed_dir, "BASE_UNIF.parquet")

df_unif.to_parquet(out_path, index=False, engine="fastparquet", compression="gzip")

df_unif

Requirement already satisfied: fastparquet in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (2024.11.0)
Requirement already satisfied: pandas>=1.5.0 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fastparquet) (2.3.2)
Requirement already satisfied: numpy in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fastparquet) (2.1.0)
Requirement already satisfied: cramjam>=2.3 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fastparquet) (2.11.0)
Requirement already satisfied: fsspec in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from fastparquet) (2025.9.0)
Requirement already satisfied: packaging in c:\users\admin\appdata\roaming\python\python312\site-packages (from fastparquet) (24.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\admin\appdata\roaming\python\python312\site-packages (from pandas>=1.5.0->fastparquet) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\admin\appdata\local\programs\python\python312\lib\site-packages (from pandas>=1.5.0->fastparquet) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\admin\appdata\roaming\python\python312\site-packages (from python-dateutil>=2.8.2->pandas>=1.5.0->fastparquet) (1.16.0)

,ID_SAEB,PROFICIENCIA_MT_SAEB,TX_RESP_Q002,TX_RESP_Q003A,TX_RESP_Q003B,TX_RESP_Q003C,TX_RESP_Q003D,TX_RESP_Q003E,TX_RESP_Q004,TX_RESP_Q005,...,TX_RESP_Q13i,TX_RESP_Q15a,TX_RESP_Q15b,TX_RESP_Q20,TX_RESP_Q21a,TX_RESP_Q21b,TX_RESP_Q21c,TX_RESP_Q21d,TX_RESP_Q21e,TX_RESP_Q24
0,2019,239.920418,A,B,B,B,A,A,A,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2019,244.042645,C,B,A,B,B,B,E,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2019,230.205828,C,B,.,.,.,.,F,F,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2019,268.977498,C,B,B,B,A,A,E,D,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2019,260.803189,A,B,B,B,A,A,B,A,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5850761,2023,241.227963,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B,.,B,A,C,B,B,A,D,C
5850762,2023,220.519967,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B,A,A,A,B,A,B,A,D,D
5850763,2023,341.751041,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B,B,.,A,B,C,A,A,D,C
5850764,2023,328.555589,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B,A,B,A,C,D,D,C,D,C
5850765,2023,220.753374,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,B,A,B,A,B,A,B,A,D,C